00:34:19 Не удалось загрузить https://kakvkusno.ru/catalog/gotovye-blyuda/
00:34:20 Проблема с валидностью контента SnowQueen.ru. 
00:34:20 Проблема с валидностью контента kakvkusno.ru. 
00:34:51 Не удалось загрузить https://mebelidomanet.ru/category/kuhonnye-garnitury
00:34:51 Проблема с валидностью контента mebelidomanet.ru. 
00:35:29 Проблема с валидностью контента SnowQueen.ru. 
00:35:29 Проблема с валидностью контента зашубой.рф. 
00:39:01 Проблема с валидностью контента santehnika-online.ru. 
00:39:28 Проблема с валидностью контента rbt.ru. 
00:39:36 Не удалось загрузить https://www.TechPort.ru/katalog/products/striralnye-mashiny
00:39:36 Проблема с валидностью контента TechPort.ru. 
00:40:56 Не удалось загрузить https://msk.dostaevsky.ru/pizza
00:40:56 Проблема с валидностью контента dostaevsky.ru. 
00:40:57 Не удалось загрузить https://zakazaka.ru/restaurants/pizza
00:40:57 Проблема с валидностью контента zakazaka.ru. 
00:40:57 Не удалось загрузить https://zakazaka.ru/restaurants
00:40:57 Проблема с валидностью контента zakazaka.ru. 
00:40:57 Не удалось загрузить https://ILPatio.ru/category/pitstsa/
00:40:57 Проблема с валидностью контента ILPatio.ru. 
00:40:57 Не удалось загрузить https://www.vprok.ru/catalog
00:40:57 Проблема с валидностью контента vprok.ru. 
00:40:57 Не удалось загрузить https://eda.yandex.ru?utm_source=Wizard&amp;utm_medium=yp&amp;utm_campaign=delivery_showcase_rest&amp;utm_content=desktop
00:40:57 Не удалось загрузить https://www.Utkonos.ru/
00:40:57 Проблема с валидностью контента Utkonos.ru. 
00:40:58 Не удалось загрузить https://moscow.big-book-relax.ru/dostavka-edy/
00:40:58 Проблема с валидностью контента big-book-relax.ru. 
00:40:58 Не удалось загрузить https://broniboy.ru/moscow/restaurants/
00:40:58 Проблема с валидностью контента broniboy.ru. 
00:40:58 Не удалось загрузить https://msk.chibbis.ru/restaurants/pizza
00:40:58 Не удалось загрузить https://tashirpizza.ru/moskva/catalog/picca
00:40:58 Проблема с валидностью контента tashirpizza.ru. 
00:40:58 Проблема с валидностью контента chibbis.ru. 
00:40:59 Не удалось загрузить https://pizzafab.ru/pizza/
00:40:59 Проблема с валидностью контента pizzafab.ru. 
00:40:59 Не удалось загрузить https://msk.chibbis.ru/restaurants
00:40:59 Проблема с валидностью контента chibbis.ru. 
00:40:59 Проблема с валидностью контента PapaJohns.ru. 
00:41:08 Не удалось загрузить https://m-food.ru/
00:41:08 Проблема с валидностью контента m-food.ru. 
00:46:19 Проблема с валидностью контента SnowQueen.ru. 
00:46:20 Проблема с валидностью контента SnowQueen.ru. 
00:47:11 Не удалось загрузить https://iPizza.ru/menu/dostavka_edy_moscow
00:47:11 Проблема с валидностью контента iPizza.ru. 
00:47:12 Не удалось загрузить https://www.okeydostavka.ru/msk/zamorozka-gotovaia-kulinariia/gotovye-bliuda
00:47:12 Не удалось загрузить https://www.Utkonos.ru/
00:47:13 Проблема с валидностью контента okeydostavka.ru. 
00:47:13 Проблема с валидностью контента Utkonos.ru. 
00:47:13 Не удалось загрузить https://www.vprok.ru/info/delivery
00:47:13 Проблема с валидностью контента vprok.ru. 
00:47:13 Не удалось загрузить https://av.ru/catalog/osoznannyy-vybor/perekusy-i-superfudy/gotovaya-kulinariya/
00:47:13 Проблема с валидностью контента av.ru. 
00:47:13 Не удалось загрузить https://msk.dostaevsky.ru/
00:47:13 Проблема с валидностью контента dostaevsky.ru. 
00:47:13 Не удалось загрузить https://kakvkusno.ru/catalog/gotovye-blyuda/
00:47:13 Проблема с валидностью контента kakvkusno.ru. 
00:47:16 Не удалось загрузить https://www.delivery-club.ru/moscow
00:47:16 Проблема с валидностью контента delivery-club.ru. 
00:47:17 Не удалось загрузить https://hochyedy.ru/
00:47:17 Проблема с валидностью контента hochyedy.ru. 
00:47:32 Не удалось загрузить https://kakvkusno.ru/catalog/gotovye-blyuda/
00:47:32 Проблема с валидностью контента kakvkusno.ru. 
00:47:52 Проблема с валидностью контента зашубой.рф. 
00:47:53 Проблема с валидностью контента SnowQueen.ru. 
00:48:01 Не удалось загрузить https://www.TechPort.ru/katalog/products/mebel/mebel-dlja-kuhni/kuhonnye-garnitury
00:48:01 Проблема с валидностью контента TechPort.ru. 
00:49:10 Проблема с валидностью контента SnowQueen.ru. 
00:49:10 Проблема с валидностью контента зашубой.рф. 
00:49:10 Не удалось загрузить https://kostroma.flagma.ru/vyvoz-musora-so219441-1.html?price=1
00:49:10 Проблема с валидностью контента flagma.ru. 
00:50:00 Проблема с валидностью контента santehnika-online.ru. 
00:50:27 Проблема с валидностью контента santehnika-online.ru. 
00:51:45 Проблема с валидностью контента PapaJohns.ru. 
00:52:12 Не удалось загрузить https://Zoozavr.detmir.ru/catalog/index/name/bed_cats/
00:52:13 Проблема с валидностью контента detmir.ru. 
00:52:13 Не удалось загрузить https://4lapy.ru/catalog/koshki/lezhaki-i-domiki-koshki/lezhaki/
00:52:13 Проблема с валидностью контента 4lapy.ru. 
00:52:16 Проблема с валидностью контента 220-volt.ru. 
00:52:42 Проблема с валидностью контента rbt.ru. 
00:53:28 Проблема с валидностью контента rbt.ru. 
00:53:28 Проблема с валидностью контента dns-shop.ru. 
16:23:45 Не удалось загрузить https://uaclips.com/rev/ремонт ноутбука xiaomi/
16:23:45 Проблема с валидностью контента uaclips.com. 
16:23:45 Проблема с валидностью контента pikabu.ru. 
16:38:39 Проблема с валидностью контента supl.biz. 
16:39:35 Проблема с валидностью контента SnowQueen.ru. 
16:40:17 Проблема с валидностью контента SnowQueen.ru. 
16:40:17 Не удалось загрузить https://moscow.flagma.ru/vyvoz-musora-so219441-1.html
16:40:18 Проблема с валидностью контента flagma.ru. 
16:41:26 Не удалось загрузить https://kakvkusno.ru/catalog/gotovye-blyuda/
16:41:26 Не удалось загрузить https://kakvkusno.ru/catalog/gotovye-blyuda/
16:41:26 Проблема с валидностью контента kakvkusno.ru. 
16:41:26 Проблема с валидностью контента kakvkusno.ru. 
16:42:05 Не удалось загрузить https://samarskayaoblast.flagma.ru/vyvoz-musora-so219441-1.html
16:42:05 Проблема с валидностью контента flagma.ru. 
16:42:40 Не удалось загрузить https://syzran.flagma.ru/santehnicheskie-raboty-o-1.html
16:42:40 Проблема с валидностью контента flagma.ru. 
16:42:41 Проблема с валидностью контента santehnika-online.ru. 
16:46:04 Не удалось загрузить https://journal.tinkoff.ru/short/beri-i-katis/
16:46:04 Проблема с валидностью контента tinkoff.ru. 
16:47:18 Проблема с валидностью контента зашубой.рф. 
16:47:19 Проблема с валидностью контента SnowQueen.ru. 
16:48:34 Проблема с валидностью контента SnowQueen.ru. 
16:48:34 Проблема с валидностью контента PapaJohns.ru. 
16:48:45 Проблема с валидностью контента 2-berega.ru. 
16:49:11 Проблема с валидностью контента сушидза.рф. 
17:10:22 Проблема с валидностью контента SnowQueen.ru. 
17:10:22 Проблема с валидностью контента SnowQueen.ru. 
17:10:32 Проблемы с доменом mehamania.ru
17:10:34 Проблемы с доменом pantera56.ru
17:10:46 Проблема с валидностью контента сушидза.рф. 
17:11:42 Проблема с валидностью контента сушидза.рф. 
17:13:56 Проблема с валидностью контента santehnika-online.ru. 
17:14:38 Проблема с валидностью контента PapaJohns.ru. 
17:17:17 Не удалось загрузить https://journal.tinkoff.ru/short/beri-i-katis/
17:17:17 Проблема с валидностью контента tinkoff.ru. 
17:17:46 Проблема с валидностью контента PapaJohns.ru. 
17:17:55 Не удалось загрузить https://okna-gigant.ru/okna/plastikovye/erkernye
17:17:55 Проблема с валидностью контента okna-gigant.ru. 
17:17:56 Проблема с валидностью контента 2-berega.ru. 
17:18:31 Не удалось загрузить https://nuzhnaeda.ru/
17:18:31 Не удалось загрузить https://nuzhnaeda.ru/menu/category-goryachee
17:18:31 Проблема с валидностью контента nuzhnaeda.ru. 
17:18:31 Проблема с валидностью контента nuzhnaeda.ru. 
17:18:57 Проблема с валидностью контента SnowQueen.ru. 
17:19:08 Не удалось загрузить https://mks2010.ru/
17:19:08 Проблема с валидностью контента mks2010.ru. 
17:19:26 Не удалось загрузить https://kakvkusno.ru/catalog/gotovye-blyuda/
17:19:27 Проблема с валидностью контента kakvkusno.ru. 
17:20:06 Не удалось загрузить https://moscow.flagma.ru/priem-stroitelnogo-musora-so798001-1.html
17:20:06 Проблема с валидностью контента flagma.ru. 
17:20:39 Проблема с валидностью контента SnowQueen.ru. 
17:21:48 Не удалось загрузить https://staryoskol.flagma.ru/vyvoz-musora-so219441-1.html
17:21:48 Проблема с валидностью контента flagma.ru. 
19:31:09 Не удалось загрузить https://www.decorwall.ru/shtory/poelementam/serkerom/
19:31:10 Проблема с валидностью контента decorwall.ru. 
22:05:33 Не удалось загрузить https://lenta.com/catalog/bakaleya/konservaciya/rybnye-konservy/f/producerscountry=latviya/
22:05:34 Проблема с валидностью контента lenta.com. 
22:05:41 An error has been caught in function 'run', process 'Process-1' (6999), thread 'MainThread' (139883138144064):
Traceback (most recent call last):

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 820, in <module>
    Manager()
    └ <function Manager at 0x7f3914345940>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 25, in __init__
    self.run_processes()
    │    └ <function Manager.run_processes at 0x7f391055a280>
    └ <__main__.Manager object at 0x7f3913665160>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 47, in run_processes
    process.start()
    │       └ <function BaseProcess.start at 0x7f391434c940>
    └ <Process name='Process-1' parent=6996 started>

  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
    │    │        │    │      └ <Process name='Process-1' parent=6996 started>
    │    │        │    └ <staticmethod object at 0x7f39144cb0a0>
    │    │        └ <Process name='Process-1' parent=6996 started>
    │    └ None
    └ <Process name='Process-1' parent=6996 started>
  File "/usr/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           │                │                            └ <Process name='Process-1' parent=6996 started>
           │                └ <function DefaultContext.get_context at 0x7f3914361430>
           └ <multiprocessing.context.DefaultContext object at 0x7f39143962b0>
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
           │     └ <Process name='Process-1' parent=6996 started>
           └ <class 'multiprocessing.popen_fork.Popen'>
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
    │    │       └ <Process name='Process-1' parent=6996 started>
    │    └ <function Popen._launch at 0x7f391058b5e0>
    └ <multiprocessing.popen_fork.Popen object at 0x7f3910586220>
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 75, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
           │           │                          └ 7
           │           └ <function BaseProcess._bootstrap at 0x7f391434e280>
           └ <Process name='Process-1' parent=6996 started>
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7f391434c8b0>
    └ <Process name='Process-1' parent=6996 started>
> File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Process name='Process-1' parent=6996 started>
    │    │        │    └ ((719, 'рижские шпроты', '<?xml version="1.0" encoding="UTF-8" ?>\n<yandexsearch version="1.0">\n  <response date="20210224T1...
    │    │        └ <Process name='Process-1' parent=6996 started>
    │    └ <function Yandex at 0x7f391055aee0>
    └ <Process name='Process-1' parent=6996 started>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 189, in __init__
    self.add_result_to_database()
    │    └ <function Yandex.add_result_to_database at 0x7f391055b700>
    └ <__main__.Yandex object at 0x7f3914330640>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 289, in add_result_to_database
    pm.custom_request_to_database_without_return(
    │  └ <function custom_request_to_database_without_return at 0x7f39105ccee0>
    └ <module 'postgres_mode' from '/home/wenfort/concurent_site_release/postgres_mode.py'>

  File "/home/wenfort/concurent_site_release/postgres_mode.py", line 94, in custom_request_to_database_without_return
    cursor.execute(sql)
    │      │       └ "UPDATE concurent_site.main_request SET site_age_concurency = 98, site_stem_concurency = 83, site_volume_concurency = 86, sit...
    │      └ <method 'execute' of 'psycopg2.extensions.cursor' objects>
    └ <cursor object at 0x7f390eb7e130; closed: 0>

psycopg2.errors.SyntaxError: syntax error at or near "WHERE"
LINE 1: ...6, site_seo_concurency = 91, request_views = 772, WHERE requ...
                                                             ^

22:06:41 Не удалось загрузить https://lenta.com/catalog/bakaleya/konservaciya/rybnye-konservy/f/producerscountry=latviya/
22:06:41 Проблема с валидностью контента lenta.com. 
22:07:31 An error has been caught in function 'make_backlinks_object', process 'Process-2' (7195), thread 'Thread-22' (139875584034560):
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f379881c430>
    └ <Thread(Thread-22, started 139875584034560)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f379881c160>
    └ <Thread(Thread-22, started 139875584034560)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-22, started 139875584034560)>
    │    │        │    └ ('22', (<doc><url>https://msk.laoshi.ru/</url><title>Курсы китайского языка Лаоши в Москве</title><passages><passage>Изучайте...
    │    │        └ <Thread(Thread-22, started 139875584034560)>
    │    └ <bound method Yandex.make_site_object of <__main__.Yandex object at 0x7f3798827640>>
    └ <Thread(Thread-22, started 139875584034560)>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 250, in make_site_object
    self.site_objects_list.append(Site(position, site))
    │    │                 │      │    │         └ (<doc><url>https://msk.laoshi.ru/</url><title>Курсы китайского языка Лаоши в Москве</title><passages><passage>Изучайте китайс...
    │    │                 │      │    └ '22'
    │    │                 │      └ <function Site at 0x7f3794a51700>
    │    │                 └ <method 'append' of 'list' objects>
    │    └ [<__main__.Site object at 0x7f379434e9a0>, <__main__.Site object at 0x7f379434eac0>, <__main__.Site object at 0x7f379434ea30>...
    └ <__main__.Yandex object at 0x7f3798827640>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 98, in __init__
    self.make_domain_object()
    │    └ <function Site.make_domain_object at 0x7f3794a51b80>
    └ <__main__.Site object at 0x7f37942c5c70>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 150, in make_domain_object
    self.domain_object = Domain(self.domain)
    │    │               │      │    └ 'laoshi.ru'
    │    │               │      └ <__main__.Site object at 0x7f37942c5c70>
    │    │               └ <function Domain at 0x7f3794a52ee0>
    │    └ ''
    └ <__main__.Site object at 0x7f37942c5c70>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 356, in __init__
    self.make_backlinks_object()
    │    └ <function Domain.make_backlinks_object at 0x7f3794a54280>
    └ <__main__.Domain object at 0x7f379434e970>

> File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 413, in make_backlinks_object
    self.backlinks_object = Backlinks(self.domain)
    │    │                  │         │    └ 'laoshi.ru'
    │    │                  │         └ <__main__.Domain object at 0x7f379434e970>
    │    │                  └ <function Backlinks at 0x7f3794a52a60>
    │    └ ''
    └ <__main__.Domain object at 0x7f379434e970>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 319, in __init__
    self.get_token()
    │    └ <function Backlinks.get_token at 0x7f3794a52b80>
    └ <__main__.Backlinks object at 0x7f377025bf40>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 324, in get_token
    self.token = accounts_with_balance[0][0]
    │    │       └ []
    │    └ ''
    └ <__main__.Backlinks object at 0x7f377025bf40>

IndexError: list index out of range
22:07:31 Проблемы с доменом laoshi.ru
22:07:31 An error has been caught in function 'make_backlinks_object', process 'Process-2' (7195), thread 'Thread-12' (139876146083584):
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f379881c430>
    └ <Thread(Thread-12, started 139876146083584)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f379881c160>
    └ <Thread(Thread-12, started 139876146083584)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-12, started 139876146083584)>
    │    │        │    └ ('12', (<doc><url>https://Zaochnik.ru/blog/kak-vyuchit-kitajskij-yazyk-samostoyatelno-doma-s-nulya-3-metoda-sovety-specialist...
    │    │        └ <Thread(Thread-12, started 139876146083584)>
    │    └ <bound method Yandex.make_site_object of <__main__.Yandex object at 0x7f3798827640>>
    └ <Thread(Thread-12, started 139876146083584)>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 250, in make_site_object
    self.site_objects_list.append(Site(position, site))
    │    │                 │      │    │         └ (<doc><url>https://Zaochnik.ru/blog/kak-vyuchit-kitajskij-yazyk-samostoyatelno-doma-s-nulya-3-metoda-sovety-specialistov/</ur...
    │    │                 │      │    └ '12'
    │    │                 │      └ <function Site at 0x7f3794a51700>
    │    │                 └ <method 'append' of 'list' objects>
    │    └ [<__main__.Site object at 0x7f379434e9a0>, <__main__.Site object at 0x7f379434eac0>, <__main__.Site object at 0x7f379434ea30>...
    └ <__main__.Yandex object at 0x7f3798827640>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 98, in __init__
    self.make_domain_object()
    │    └ <function Site.make_domain_object at 0x7f3794a51b80>
    └ <__main__.Site object at 0x7f37943005b0>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 150, in make_domain_object
    self.domain_object = Domain(self.domain)
    │    │               │      │    └ 'Zaochnik.ru'
    │    │               │      └ <__main__.Site object at 0x7f37943005b0>
    │    │               └ <function Domain at 0x7f3794a52ee0>
    │    └ ''
    └ <__main__.Site object at 0x7f37943005b0>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 356, in __init__
    self.make_backlinks_object()
    │    └ <function Domain.make_backlinks_object at 0x7f3794a54280>
    └ <__main__.Domain object at 0x7f37335d0700>

> File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 413, in make_backlinks_object
    self.backlinks_object = Backlinks(self.domain)
    │    │                  │         │    └ 'Zaochnik.ru'
    │    │                  │         └ <__main__.Domain object at 0x7f37335d0700>
    │    │                  └ <function Backlinks at 0x7f3794a52a60>
    │    └ ''
    └ <__main__.Domain object at 0x7f37335d0700>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 319, in __init__
    self.get_token()
    │    └ <function Backlinks.get_token at 0x7f3794a52b80>
    └ <__main__.Backlinks object at 0x7f37942dadc0>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 324, in get_token
    self.token = accounts_with_balance[0][0]
    │    │       └ []
    │    └ ''
    └ <__main__.Backlinks object at 0x7f37942dadc0>

IndexError: list index out of range
22:07:31 Проблемы с доменом Zaochnik.ru
22:07:31 An error has been caught in function 'make_backlinks_object', process 'Process-2' (7195), thread 'Thread-16' (139876112512768):
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f379881c430>
    └ <Thread(Thread-16, started 139876112512768)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f379881c160>
    └ <Thread(Thread-16, started 139876112512768)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-16, started 139876112512768)>
    │    │        │    └ ('16', (<doc><url>https://info-profi.net/kitajskij-yazyk/</url><title>Как выучить китайский язык самостоятельно дома с нуля</...
    │    │        └ <Thread(Thread-16, started 139876112512768)>
    │    └ <bound method Yandex.make_site_object of <__main__.Yandex object at 0x7f3798827640>>
    └ <Thread(Thread-16, started 139876112512768)>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 250, in make_site_object
    self.site_objects_list.append(Site(position, site))
    │    │                 │      │    │         └ (<doc><url>https://info-profi.net/kitajskij-yazyk/</url><title>Как выучить китайский язык самостоятельно дома с нуля</title><...
    │    │                 │      │    └ '16'
    │    │                 │      └ <function Site at 0x7f3794a51700>
    │    │                 └ <method 'append' of 'list' objects>
    │    └ [<__main__.Site object at 0x7f379434e9a0>, <__main__.Site object at 0x7f379434eac0>, <__main__.Site object at 0x7f379434ea30>...
    └ <__main__.Yandex object at 0x7f3798827640>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 98, in __init__
    self.make_domain_object()
    │    └ <function Site.make_domain_object at 0x7f3794a51b80>
    └ <__main__.Site object at 0x7f3794317ee0>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 150, in make_domain_object
    self.domain_object = Domain(self.domain)
    │    │               │      │    └ 'info-profi.net'
    │    │               │      └ <__main__.Site object at 0x7f3794317ee0>
    │    │               └ <function Domain at 0x7f3794a52ee0>
    │    └ ''
    └ <__main__.Site object at 0x7f3794317ee0>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 356, in __init__
    self.make_backlinks_object()
    │    └ <function Domain.make_backlinks_object at 0x7f3794a54280>
    └ <__main__.Domain object at 0x7f37501dbd30>

> File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 413, in make_backlinks_object
    self.backlinks_object = Backlinks(self.domain)
    │    │                  │         │    └ 'info-profi.net'
    │    │                  │         └ <__main__.Domain object at 0x7f37501dbd30>
    │    │                  └ <function Backlinks at 0x7f3794a52a60>
    │    └ ''
    └ <__main__.Domain object at 0x7f37501dbd30>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 319, in __init__
    self.get_token()
    │    └ <function Backlinks.get_token at 0x7f3794a52b80>
    └ <__main__.Backlinks object at 0x7f3793d34070>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 324, in get_token
    self.token = accounts_with_balance[0][0]
    │    │       └ []
    │    └ ''
    └ <__main__.Backlinks object at 0x7f3793d34070>

IndexError: list index out of range
22:07:31 Проблемы с доменом info-profi.net
22:07:31 An error has been caught in function 'make_backlinks_object', process 'Process-2' (7195), thread 'Thread-21' (139875592427264):
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f379881c430>
    └ <Thread(Thread-21, started 139875592427264)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f379881c160>
    └ <Thread(Thread-21, started 139875592427264)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-21, started 139875592427264)>
    │    │        │    └ ('21', (<doc><url>https://ichinese8.ru/chinese-free/</url><title>Учить китайский бесплатно: 40+ способов</title><passages><pa...
    │    │        └ <Thread(Thread-21, started 139875592427264)>
    │    └ <bound method Yandex.make_site_object of <__main__.Yandex object at 0x7f3798827640>>
    └ <Thread(Thread-21, started 139875592427264)>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 250, in make_site_object
    self.site_objects_list.append(Site(position, site))
    │    │                 │      │    │         └ (<doc><url>https://ichinese8.ru/chinese-free/</url><title>Учить китайский бесплатно: 40+ способов</title><passages><passage>В...
    │    │                 │      │    └ '21'
    │    │                 │      └ <function Site at 0x7f3794a51700>
    │    │                 └ <method 'append' of 'list' objects>
    │    └ [<__main__.Site object at 0x7f379434e9a0>, <__main__.Site object at 0x7f379434eac0>, <__main__.Site object at 0x7f379434ea30>...
    └ <__main__.Yandex object at 0x7f3798827640>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 98, in __init__
    self.make_domain_object()
    │    └ <function Site.make_domain_object at 0x7f3794a51b80>
    └ <__main__.Site object at 0x7f37942c5220>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 150, in make_domain_object
    self.domain_object = Domain(self.domain)
    │    │               │      │    └ 'ichinese8.ru'
    │    │               │      └ <__main__.Site object at 0x7f37942c5220>
    │    │               └ <function Domain at 0x7f3794a52ee0>
    │    └ ''
    └ <__main__.Site object at 0x7f37942c5220>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 356, in __init__
    self.make_backlinks_object()
    │    └ <function Domain.make_backlinks_object at 0x7f3794a54280>
    └ <__main__.Domain object at 0x7f3770263280>

> File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 413, in make_backlinks_object
    self.backlinks_object = Backlinks(self.domain)
    │    │                  │         │    └ 'ichinese8.ru'
    │    │                  │         └ <__main__.Domain object at 0x7f3770263280>
    │    │                  └ <function Backlinks at 0x7f3794a52a60>
    │    └ ''
    └ <__main__.Domain object at 0x7f3770263280>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 319, in __init__
    self.get_token()
    │    └ <function Backlinks.get_token at 0x7f3794a52b80>
    └ <__main__.Backlinks object at 0x7f37335d00a0>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 324, in get_token
    self.token = accounts_with_balance[0][0]
    │    │       └ []
    │    └ ''
    └ <__main__.Backlinks object at 0x7f37335d00a0>

IndexError: list index out of range
22:07:31 Проблемы с доменом ichinese8.ru
22:07:32 An error has been caught in function 'make_backlinks_object', process 'Process-2' (7195), thread 'Thread-5' (139876668348160):
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f379881c430>
    └ <Thread(Thread-5, started 139876668348160)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f379881c160>
    └ <Thread(Thread-5, started 139876668348160)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-5, started 139876668348160)>
    │    │        │    └ ('5', (<doc><url>https://lingust.ru/chinese/chinese-lessons</url><title>Уроки китайского языка для начинающих</title><passage...
    │    │        └ <Thread(Thread-5, started 139876668348160)>
    │    └ <bound method Yandex.make_site_object of <__main__.Yandex object at 0x7f3798827640>>
    └ <Thread(Thread-5, started 139876668348160)>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 250, in make_site_object
    self.site_objects_list.append(Site(position, site))
    │    │                 │      │    │         └ (<doc><url>https://lingust.ru/chinese/chinese-lessons</url><title>Уроки китайского языка для начинающих</title><passages><pas...
    │    │                 │      │    └ '5'
    │    │                 │      └ <function Site at 0x7f3794a51700>
    │    │                 └ <method 'append' of 'list' objects>
    │    └ [<__main__.Site object at 0x7f379434e9a0>, <__main__.Site object at 0x7f379434eac0>, <__main__.Site object at 0x7f379434ea30>...
    └ <__main__.Yandex object at 0x7f3798827640>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 98, in __init__
    self.make_domain_object()
    │    └ <function Site.make_domain_object at 0x7f3794a51b80>
    └ <__main__.Site object at 0x7f379434e9d0>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 150, in make_domain_object
    self.domain_object = Domain(self.domain)
    │    │               │      │    └ 'lingust.ru'
    │    │               │      └ <__main__.Site object at 0x7f379434e9d0>
    │    │               └ <function Domain at 0x7f3794a52ee0>
    │    └ ''
    └ <__main__.Site object at 0x7f379434e9d0>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 356, in __init__
    self.make_backlinks_object()
    │    └ <function Domain.make_backlinks_object at 0x7f3794a54280>
    └ <__main__.Domain object at 0x7f37335d0df0>

> File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 413, in make_backlinks_object
    self.backlinks_object = Backlinks(self.domain)
    │    │                  │         │    └ 'lingust.ru'
    │    │                  │         └ <__main__.Domain object at 0x7f37335d0df0>
    │    │                  └ <function Backlinks at 0x7f3794a52a60>
    │    └ ''
    └ <__main__.Domain object at 0x7f37335d0df0>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 319, in __init__
    self.get_token()
    │    └ <function Backlinks.get_token at 0x7f3794a52b80>
    └ <__main__.Backlinks object at 0x7f37702631f0>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 324, in get_token
    self.token = accounts_with_balance[0][0]
    │    │       └ []
    │    └ ''
    └ <__main__.Backlinks object at 0x7f37702631f0>

IndexError: list index out of range
22:07:32 Проблемы с доменом lingust.ru
22:07:32 An error has been caught in function 'make_backlinks_object', process 'Process-2' (7195), thread 'Thread-11' (139876626384640):
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f379881c430>
    └ <Thread(Thread-11, started 139876626384640)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f379881c160>
    └ <Thread(Thread-11, started 139876626384640)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-11, started 139876626384640)>
    │    │        │    └ ('11', (<doc><url>https://kursy-kitajskogo-yazyka.ru/</url><title>ТОП 5 лучших курсов китайского языка в Москве ...</title><p...
    │    │        └ <Thread(Thread-11, started 139876626384640)>
    │    └ <bound method Yandex.make_site_object of <__main__.Yandex object at 0x7f3798827640>>
    └ <Thread(Thread-11, started 139876626384640)>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 250, in make_site_object
    self.site_objects_list.append(Site(position, site))
    │    │                 │      │    │         └ (<doc><url>https://kursy-kitajskogo-yazyka.ru/</url><title>ТОП 5 лучших курсов китайского языка в Москве ...</title><passages...
    │    │                 │      │    └ '11'
    │    │                 │      └ <function Site at 0x7f3794a51700>
    │    │                 └ <method 'append' of 'list' objects>
    │    └ [<__main__.Site object at 0x7f379434e9a0>, <__main__.Site object at 0x7f379434eac0>, <__main__.Site object at 0x7f379434ea30>...
    └ <__main__.Yandex object at 0x7f3798827640>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 98, in __init__
    self.make_domain_object()
    │    └ <function Site.make_domain_object at 0x7f3794a51b80>
    └ <__main__.Site object at 0x7f3794376b80>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 150, in make_domain_object
    self.domain_object = Domain(self.domain)
    │    │               │      │    └ 'kursy-kitajskogo-yazyka.ru'
    │    │               │      └ <__main__.Site object at 0x7f3794376b80>
    │    │               └ <function Domain at 0x7f3794a52ee0>
    │    └ ''
    └ <__main__.Site object at 0x7f3794376b80>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 356, in __init__
    self.make_backlinks_object()
    │    └ <function Domain.make_backlinks_object at 0x7f3794a54280>
    └ <__main__.Domain object at 0x7f37339f3c10>

> File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 413, in make_backlinks_object
    self.backlinks_object = Backlinks(self.domain)
    │    │                  │         │    └ 'kursy-kitajskogo-yazyka.ru'
    │    │                  │         └ <__main__.Domain object at 0x7f37339f3c10>
    │    │                  └ <function Backlinks at 0x7f3794a52a60>
    │    └ ''
    └ <__main__.Domain object at 0x7f37339f3c10>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 319, in __init__
    self.get_token()
    │    └ <function Backlinks.get_token at 0x7f3794a52b80>
    └ <__main__.Backlinks object at 0x7f379423ebe0>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 324, in get_token
    self.token = accounts_with_balance[0][0]
    │    │       └ []
    │    └ ''
    └ <__main__.Backlinks object at 0x7f379423ebe0>

IndexError: list index out of range
22:07:32 Проблемы с доменом kursy-kitajskogo-yazyka.ru
22:07:32 An error has been caught in function 'make_backlinks_object', process 'Process-2' (7195), thread 'Thread-10' (139876634777344):
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f379881c430>
    └ <Thread(Thread-10, started 139876634777344)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f379881c160>
    └ <Thread(Thread-10, started 139876634777344)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-10, started 139876634777344)>
    │    │        │    └ ('10', (<doc><url>https://mymandarin.ru/kursy-kitajskogo-jazyka/</url><title>Школа изучения китайского языка в Москве | Языко...
    │    │        └ <Thread(Thread-10, started 139876634777344)>
    │    └ <bound method Yandex.make_site_object of <__main__.Yandex object at 0x7f3798827640>>
    └ <Thread(Thread-10, started 139876634777344)>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 250, in make_site_object
    self.site_objects_list.append(Site(position, site))
    │    │                 │      │    │         └ (<doc><url>https://mymandarin.ru/kursy-kitajskogo-jazyka/</url><title>Школа изучения китайского языка в Москве | Языковой...<...
    │    │                 │      │    └ '10'
    │    │                 │      └ <function Site at 0x7f3794a51700>
    │    │                 └ <method 'append' of 'list' objects>
    │    └ [<__main__.Site object at 0x7f379434e9a0>, <__main__.Site object at 0x7f379434eac0>, <__main__.Site object at 0x7f379434ea30>...
    └ <__main__.Yandex object at 0x7f3798827640>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 98, in __init__
    self.make_domain_object()
    │    └ <function Site.make_domain_object at 0x7f3794a51b80>
    └ <__main__.Site object at 0x7f379436bd60>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 150, in make_domain_object
    self.domain_object = Domain(self.domain)
    │    │               │      │    └ 'mymandarin.ru'
    │    │               │      └ <__main__.Site object at 0x7f379436bd60>
    │    │               └ <function Domain at 0x7f3794a52ee0>
    │    └ ''
    └ <__main__.Site object at 0x7f379436bd60>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 356, in __init__
    self.make_backlinks_object()
    │    └ <function Domain.make_backlinks_object at 0x7f3794a54280>
    └ <__main__.Domain object at 0x7f377254cd30>

> File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 413, in make_backlinks_object
    self.backlinks_object = Backlinks(self.domain)
    │    │                  │         │    └ 'mymandarin.ru'
    │    │                  │         └ <__main__.Domain object at 0x7f377254cd30>
    │    │                  └ <function Backlinks at 0x7f3794a52a60>
    │    └ ''
    └ <__main__.Domain object at 0x7f377254cd30>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 319, in __init__
    self.get_token()
    │    └ <function Backlinks.get_token at 0x7f3794a52b80>
    └ <__main__.Backlinks object at 0x7f3794356190>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 324, in get_token
    self.token = accounts_with_balance[0][0]
    │    │       └ []
    │    └ ''
    └ <__main__.Backlinks object at 0x7f3794356190>

IndexError: list index out of range
22:07:32 Проблемы с доменом mymandarin.ru
22:07:32 An error has been caught in function 'make_backlinks_object', process 'Process-2' (7195), thread 'Thread-23' (139875575641856):
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f379881c430>
    └ <Thread(Thread-23, started 139875575641856)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f379881c160>
    └ <Thread(Thread-23, started 139875575641856)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-23, started 139875575641856)>
    │    │        │    └ ('23', (<doc><url>https://vse-kursy.com/read/12-saity-dlya-izucheniya-kitaiskogo-yazyka.html</url><title>17 бесплатных онлайн...
    │    │        └ <Thread(Thread-23, started 139875575641856)>
    │    └ <bound method Yandex.make_site_object of <__main__.Yandex object at 0x7f3798827640>>
    └ <Thread(Thread-23, started 139875575641856)>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 250, in make_site_object
    self.site_objects_list.append(Site(position, site))
    │    │                 │      │    │         └ (<doc><url>https://vse-kursy.com/read/12-saity-dlya-izucheniya-kitaiskogo-yazyka.html</url><title>17 бесплатных онлайн-курсов...
    │    │                 │      │    └ '23'
    │    │                 │      └ <function Site at 0x7f3794a51700>
    │    │                 └ <method 'append' of 'list' objects>
    │    └ [<__main__.Site object at 0x7f379434e9a0>, <__main__.Site object at 0x7f379434eac0>, <__main__.Site object at 0x7f379434ea30>...
    └ <__main__.Yandex object at 0x7f3798827640>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 98, in __init__
    self.make_domain_object()
    │    └ <function Site.make_domain_object at 0x7f3794a51b80>
    └ <__main__.Site object at 0x7f37942ce6a0>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 150, in make_domain_object
    self.domain_object = Domain(self.domain)
    │    │               │      │    └ 'vse-kursy.com'
    │    │               │      └ <__main__.Site object at 0x7f37942ce6a0>
    │    │               └ <function Domain at 0x7f3794a52ee0>
    │    └ ''
    └ <__main__.Site object at 0x7f37942ce6a0>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 356, in __init__
    self.make_backlinks_object()
    │    └ <function Domain.make_backlinks_object at 0x7f3794a54280>
    └ <__main__.Domain object at 0x7f3733df6f10>

> File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 413, in make_backlinks_object
    self.backlinks_object = Backlinks(self.domain)
    │    │                  │         │    └ 'vse-kursy.com'
    │    │                  │         └ <__main__.Domain object at 0x7f3733df6f10>
    │    │                  └ <function Backlinks at 0x7f3794a52a60>
    │    └ ''
    └ <__main__.Domain object at 0x7f3733df6f10>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 319, in __init__
    self.get_token()
    │    └ <function Backlinks.get_token at 0x7f3794a52b80>
    └ <__main__.Backlinks object at 0x7f3794300fa0>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 324, in get_token
    self.token = accounts_with_balance[0][0]
    │    │       └ []
    │    └ ''
    └ <__main__.Backlinks object at 0x7f3794300fa0>

IndexError: list index out of range
22:07:32 Проблемы с доменом vse-kursy.com
22:07:32 An error has been caught in function 'make_backlinks_object', process 'Process-2' (7195), thread 'Thread-17' (139876104120064):
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f379881c430>
    └ <Thread(Thread-17, started 139876104120064)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f379881c160>
    └ <Thread(Thread-17, started 139876104120064)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-17, started 139876104120064)>
    │    │        │    └ ('17', (<doc><url>https://bubolab.ru/articles/kitajskij-yazyk-dlya-nachinayuschih-s-nulya-samouchitel/</url><title>Китайский ...
    │    │        └ <Thread(Thread-17, started 139876104120064)>
    │    └ <bound method Yandex.make_site_object of <__main__.Yandex object at 0x7f3798827640>>
    └ <Thread(Thread-17, started 139876104120064)>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 250, in make_site_object
    self.site_objects_list.append(Site(position, site))
    │    │                 │      │    │         └ (<doc><url>https://bubolab.ru/articles/kitajskij-yazyk-dlya-nachinayuschih-s-nulya-samouchitel/</url><title>Китайский язык с ...
    │    │                 │      │    └ '17'
    │    │                 │      └ <function Site at 0x7f3794a51700>
    │    │                 └ <method 'append' of 'list' objects>
    │    └ [<__main__.Site object at 0x7f379434e9a0>, <__main__.Site object at 0x7f379434eac0>, <__main__.Site object at 0x7f379434ea30>...
    └ <__main__.Yandex object at 0x7f3798827640>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 98, in __init__
    self.make_domain_object()
    │    └ <function Site.make_domain_object at 0x7f3794a51b80>
    └ <__main__.Site object at 0x7f3794323910>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 150, in make_domain_object
    self.domain_object = Domain(self.domain)
    │    │               │      │    └ 'bubolab.ru'
    │    │               │      └ <__main__.Site object at 0x7f3794323910>
    │    │               └ <function Domain at 0x7f3794a52ee0>
    │    └ ''
    └ <__main__.Site object at 0x7f3794323910>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 356, in __init__
    self.make_backlinks_object()
    │    └ <function Domain.make_backlinks_object at 0x7f3794a54280>
    └ <__main__.Domain object at 0x7f37941ee7c0>

> File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 413, in make_backlinks_object
    self.backlinks_object = Backlinks(self.domain)
    │    │                  │         │    └ 'bubolab.ru'
    │    │                  │         └ <__main__.Domain object at 0x7f37941ee7c0>
    │    │                  └ <function Backlinks at 0x7f3794a52a60>
    │    └ ''
    └ <__main__.Domain object at 0x7f37941ee7c0>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 319, in __init__
    self.get_token()
    │    └ <function Backlinks.get_token at 0x7f3794a52b80>
    └ <__main__.Backlinks object at 0x7f37941ee160>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 324, in get_token
    self.token = accounts_with_balance[0][0]
    │    │       └ []
    │    └ ''
    └ <__main__.Backlinks object at 0x7f37941ee160>

IndexError: list index out of range
22:07:32 Проблемы с доменом bubolab.ru
22:15:08 Проблема с валидностью контента wikichi.ru. 
22:15:08 Проблема с валидностью контента wikichi.ru. 
22:15:12 Проблема с валидностью контента trsk.info. 
22:15:46 Проблема с валидностью контента wikichi.ru. 
19:08:27 An error has been caught in function 'run', process 'Process-1' (8527), thread 'MainThread' (139918343821120):
Traceback (most recent call last):

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 824, in <module>
    Manager()
    └ <function Manager at 0x7f4146a079d0>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 25, in __init__
    self.run_processes()
    │    └ <function Manager.run_processes at 0x7f4142c1a310>
    └ <__main__.Manager object at 0x7f4145d25370>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 47, in run_processes
    process.start()
    │       └ <function BaseProcess.start at 0x7f4146a0c9d0>
    └ <Process name='Process-1' parent=8467 started>

  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
    │    │        │    │      └ <Process name='Process-1' parent=8467 started>
    │    │        │    └ <staticmethod object at 0x7f4146b8b070>
    │    │        └ <Process name='Process-1' parent=8467 started>
    │    └ None
    └ <Process name='Process-1' parent=8467 started>
  File "/usr/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           │                │                            └ <Process name='Process-1' parent=8467 started>
           │                └ <function DefaultContext.get_context at 0x7f4146a214c0>
           └ <multiprocessing.context.DefaultContext object at 0x7f4146a56280>
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
           │     └ <Process name='Process-1' parent=8467 started>
           └ <class 'multiprocessing.popen_fork.Popen'>
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
    │    │       └ <Process name='Process-1' parent=8467 started>
    │    └ <function Popen._launch at 0x7f4142c47700>
    └ <multiprocessing.popen_fork.Popen object at 0x7f4142c43430>
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 75, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
           │           │                          └ 7
           │           └ <function BaseProcess._bootstrap at 0x7f4146a50310>
           └ <Process name='Process-1' parent=8467 started>
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7f4146a0c940>
    └ <Process name='Process-1' parent=8467 started>
> File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Process name='Process-1' parent=8467 started>
    │    │        │    └ ((724, 'как сделать йогурт', '<?xml version="1.0" encoding="UTF-8" ?>\n<yandexsearch version="1.0">\n  <response date="202102...
    │    │        └ <Process name='Process-1' parent=8467 started>
    │    └ <function Yandex at 0x7f4142c1af70>
    └ <Process name='Process-1' parent=8467 started>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 189, in __init__
    self.add_result_to_database()
    │    └ <function Yandex.add_result_to_database at 0x7f4142c1b790>
    └ <__main__.Yandex object at 0x7f41469eec10>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 293, in add_result_to_database
    pm.custom_request_to_database_without_return(
    │  └ <function custom_request_to_database_without_return at 0x7f4142c15f70>
    └ <module 'postgres_mode' from '/home/wenfort/concurent_site_release/postgres_mode.py'>

  File "/home/wenfort/concurent_site_release/postgres_mode.py", line 94, in custom_request_to_database_without_return
    cursor.execute(sql)
    │      │       └ "UPDATE concurent_site.main_request SET site_age_concurency = 90, site_stem_concurency = 69, site_volume_concurency = 93, sit...
    │      └ <method 'execute' of 'psycopg2.extensions.cursor' objects>
    └ <cursor object at 0x7f41103499a0; closed: 0>

psycopg2.errors.SyntaxError: syntax error at or near "тыс"
LINE 1: ... 6, site_seo_concurency = 0, request_views = ~1.1 тыс WHERE ...
                                                             ^

22:23:36 Проблемы с доменом consultant-mos.ru
22:23:37 Проблемы с доменом kaom.ru
22:23:39 Проблемы с доменом jurexpertcenter.ru
03:55:27 Не удалось загрузить https://zdr.ru/articles/uluchshit-zrenie-vam-eto-pod-silu
03:55:27 Проблема с валидностью контента zdr.ru. 
12:11:35 An error has been caught in function 'run', process 'Process-1' (10673), thread 'MainThread' (140164933531456):
Traceback (most recent call last):

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 857, in <module>
    Manager()
    └ <function Manager at 0x7f7ab07e2a60>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 25, in __init__
    self.run_processes()
    │    └ <function Manager.run_processes at 0x7f7aacad2280>
    └ <__main__.Manager object at 0x7f7aafb6a2e0>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 47, in run_processes
    process.start()
    │       └ <function BaseProcess.start at 0x7f7ab08149d0>
    └ <Process name='Process-1' parent=10666 started>

  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
    │    │        │    │      └ <Process name='Process-1' parent=10666 started>
    │    │        │    └ <staticmethod object at 0x7f7ab09ce070>
    │    │        └ <Process name='Process-1' parent=10666 started>
    │    └ None
    └ <Process name='Process-1' parent=10666 started>
  File "/usr/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           │                │                            └ <Process name='Process-1' parent=10666 started>
           │                └ <function DefaultContext.get_context at 0x7f7ab0868430>
           └ <multiprocessing.context.DefaultContext object at 0x7f7ab089f280>
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
           │     └ <Process name='Process-1' parent=10666 started>
           └ <class 'multiprocessing.popen_fork.Popen'>
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
    │    │       └ <Process name='Process-1' parent=10666 started>
    │    └ <function Popen._launch at 0x7f7aaca905e0>
    └ <multiprocessing.popen_fork.Popen object at 0x7f7aaca8a3a0>
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 75, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
           │           │                          └ 7
           │           └ <function BaseProcess._bootstrap at 0x7f7ab0899310>
           └ <Process name='Process-1' parent=10666 started>
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7f7ab0814940>
    └ <Process name='Process-1' parent=10666 started>
> File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Process name='Process-1' parent=10666 started>
    │    │        │    └ ((1245, 'коррекция зрения', '<?xml version="1.0" encoding="UTF-8" ?>\n<yandexsearch version="1.0">\n  <response date="2021030...
    │    │        └ <Process name='Process-1' parent=10666 started>
    │    └ <function Yandex at 0x7f7aacad2ee0>
    └ <Process name='Process-1' parent=10666 started>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 192, in __init__
    self.add_result_to_database()
    │    └ <function Yandex.add_result_to_database at 0x7f7aaca60700>
    └ <__main__.Yandex object at 0x7f7ab0802be0>

  File "/home/wenfort/concurent_site_release/new_requests_handler.py", line 296, in add_result_to_database
    pm.custom_request_to_database_without_return(
    │  └ <function custom_request_to_database_without_return at 0x7f7aacad3ee0>
    └ <module 'postgres_mode' from '/home/wenfort/concurent_site_release/postgres_mode.py'>

  File "/home/wenfort/concurent_site_release/postgres_mode.py", line 94, in custom_request_to_database_without_return
    cursor.execute(sql)
    │      │       └ "UPDATE concurent_site.main_request SET site_age_concurency = 96, site_stem_concurency = 100, site_volume_concurency = 98, si...
    │      └ <method 'execute' of 'psycopg2.extensions.cursor' objects>
    └ <cursor object at 0x7f7aaa76d040; closed: 0>

psycopg2.errors.SyntaxError: syntax error at or near "average_age"
LINE 1: ... site_seo_concurency = 96, request_views = 191000 average_ag...
                                                             ^

12:38:14 Проблема с валидностью контента twitter.com. 
12:38:23 Проблемы с доменом riotpixels.com
12:40:22 Проблемы с доменом mihoyo.com
12:18:59 Не удалось загрузить https://www.nlv.ru/laser-correction/lasik-operatsiya
12:19:00 Проблема с валидностью контента nlv.ru. 
12:22:33 Не удалось загрузить https://www.nlv.ru/laser-correction/lasik-operatsiya
12:22:33 Проблема с валидностью контента nlv.ru. 
12:24:11 Не удалось загрузить https://www.nlv.ru/laser-correction
12:24:11 Проблема с валидностью контента nlv.ru. 
12:25:46 Не удалось загрузить https://www.nlv.ru/laser-correction
12:25:46 Проблема с валидностью контента nlv.ru. 
12:30:58 Не удалось загрузить https://www.nlv.ru/laser-correction
12:30:58 Проблема с валидностью контента nlv.ru. 
14:42:50 Не удалось загрузить https://www.nlv.ru/laser-correction/lasik-operatsiya
14:42:50 Проблема с валидностью контента nlv.ru. 
14:43:30 Не удалось загрузить https://www.nlv.ru/laser-correction/lasik-operatsiya
14:43:30 Проблема с валидностью контента nlv.ru. 
11:44:02 An error has been caught in function 'run', process 'Process-1' (5371), thread 'MainThread' (140250365544256):
Traceback (most recent call last):

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 887, in <module>
    Manager()
    └ <function Manager at 0x7f8e94a1e550>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 25, in __init__
    self.run_processes()
    │    └ <function Manager.run_processes at 0x7f8e90ca8ca0>
    └ <__main__.Manager object at 0x7f8e93dafdf0>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 47, in run_processes
    process.start()
    │       └ <function BaseProcess.start at 0x7f8e94a70040>
    └ <Process name='Process-1' parent=5369 started>

  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
    │    │        │    │      └ <Process name='Process-1' parent=5369 started>
    │    │        │    └ <staticmethod object at 0x7f8e949fc760>
    │    │        └ <Process name='Process-1' parent=5369 started>
    │    └ None
    └ <Process name='Process-1' parent=5369 started>
  File "/usr/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           │                │                            └ <Process name='Process-1' parent=5369 started>
           │                └ <function DefaultContext.get_context at 0x7f8e94a56160>
           └ <multiprocessing.context.DefaultContext object at 0x7f8e94a77100>
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
           │     └ <Process name='Process-1' parent=5369 started>
           └ <class 'multiprocessing.popen_fork.Popen'>
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
    │    │       └ <Process name='Process-1' parent=5369 started>
    │    └ <function Popen._launch at 0x7f8e90c4e0d0>
    └ <multiprocessing.popen_fork.Popen object at 0x7f8e90cd0d90>
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 75, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
           │           │                          └ 7
           │           └ <function BaseProcess._bootstrap at 0x7f8e94a70940>
           └ <Process name='Process-1' parent=5369 started>
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7f8e94a66f70>
    └ <Process name='Process-1' parent=5369 started>
> File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Process name='Process-1' parent=5369 started>
    │    │        │    └ ((1247, 'lasik', '<?xml version="1.0" encoding="UTF-8" ?>\n<yandexsearch version="1.0">\n  <response date="20210320T094334"><...
    │    │        └ <Process name='Process-1' parent=5369 started>
    │    └ <function Yandex at 0x7f8e90cac940>
    └ <Process name='Process-1' parent=5369 started>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 192, in __init__
    self.add_result_to_database()
    │    └ <function Yandex.add_result_to_database at 0x7f8e90cad160>
    └ <__main__.Yandex object at 0x7f8e94a20d60>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 296, in add_result_to_database
    pm.custom_request_to_database_without_return(
    │  └ <function custom_request_to_database_without_return at 0x7f8e90ca8940>
    └ <module 'postgres_mode' from '/home/artur/concurent_site_release/postgres_mode.py'>

  File "/home/artur/concurent_site_release/postgres_mode.py", line 94, in custom_request_to_database_without_return
    cursor.execute(sql)
    │      │       └ "UPDATE concurent_site.main_request SET site_age_concurency = 94, site_stem_concurency = 94, site_volume_concurency = 98, sit...
    │      └ <method 'execute' of 'psycopg2.extensions.cursor' objects>
    └ <cursor object at 0x7f8e8dbc28b0; closed: 0>

psycopg2.errors.SyntaxError: syntax error at or near "yandex"
LINE 1: ...ique_backlinks = 427, vital_sites = wikipedia.org yandex.ru ...
                                                             ^

11:44:43 An error has been caught in function 'run', process 'Process-1' (5463), thread 'MainThread' (139918137661248):
Traceback (most recent call last):

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 887, in <module>
    Manager()
    └ <function Manager at 0x7f413a4eb550>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 25, in __init__
    self.run_processes()
    │    └ <function Manager.run_processes at 0x7f4136775ca0>
    └ <__main__.Manager object at 0x7f413987d790>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 47, in run_processes
    process.start()
    │       └ <function BaseProcess.start at 0x7f413a53f040>
    └ <Process name='Process-1' parent=5461 started>

  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
    │    │        │    │      └ <Process name='Process-1' parent=5461 started>
    │    │        │    └ <staticmethod object at 0x7f413a4c8760>
    │    │        └ <Process name='Process-1' parent=5461 started>
    │    └ None
    └ <Process name='Process-1' parent=5461 started>
  File "/usr/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           │                │                            └ <Process name='Process-1' parent=5461 started>
           │                └ <function DefaultContext.get_context at 0x7f413a664160>
           └ <multiprocessing.context.DefaultContext object at 0x7f413a546100>
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
           │     └ <Process name='Process-1' parent=5461 started>
           └ <class 'multiprocessing.popen_fork.Popen'>
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
    │    │       └ <Process name='Process-1' parent=5461 started>
    │    └ <function Popen._launch at 0x7f41367ae0d0>
    └ <multiprocessing.popen_fork.Popen object at 0x7f41367a5bb0>
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 75, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
           │           │                          └ 7
           │           └ <function BaseProcess._bootstrap at 0x7f413a53f940>
           └ <Process name='Process-1' parent=5461 started>
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7f413a534f70>
    └ <Process name='Process-1' parent=5461 started>
> File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Process name='Process-1' parent=5461 started>
    │    │        │    └ ((1247, 'lasik', '<?xml version="1.0" encoding="UTF-8" ?>\n<yandexsearch version="1.0">\n  <response date="20210320T094334"><...
    │    │        └ <Process name='Process-1' parent=5461 started>
    │    └ <function Yandex at 0x7f413677a940>
    └ <Process name='Process-1' parent=5461 started>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 192, in __init__
    self.add_result_to_database()
    │    └ <function Yandex.add_result_to_database at 0x7f413677b160>
    └ <__main__.Yandex object at 0x7f413a4ecd60>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 296, in add_result_to_database
    pm.custom_request_to_database_without_return(
    │  └ <function custom_request_to_database_without_return at 0x7f4136775940>
    └ <module 'postgres_mode' from '/home/artur/concurent_site_release/postgres_mode.py'>

  File "/home/artur/concurent_site_release/postgres_mode.py", line 94, in custom_request_to_database_without_return
    cursor.execute(sql)
    │      │       └ "UPDATE concurent_site.main_request SET site_age_concurency = 94, site_stem_concurency = 94, site_volume_concurency = 98, sit...
    │      └ <method 'execute' of 'psycopg2.extensions.cursor' objects>
    └ <cursor object at 0x7f412e227b80; closed: 0>

psycopg2.errors.StringDataRightTruncation: value too long for type character varying(100)

12:45:12 Проблема с валидностью контента ppl-14.ru. 
12:58:58 Проблема с валидностью контента ppl-14.ru. 
16:14:46 Не удалось загрузить https://www.nlv.ru/laser-correction
16:14:46 Проблема с валидностью контента nlv.ru. 
16:14:53 An error has been caught in function 'make_concurency_object', process 'Process-1' (25600), thread 'MainThread' (139812300470080):
Traceback (most recent call last):

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 887, in <module>
    Manager()
    └ <function Manager at 0x7f2895eb6550>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 25, in __init__
    self.run_processes()
    │    └ <function Manager.run_processes at 0x7f289213fca0>
    └ <__main__.Manager object at 0x7f28952476a0>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 47, in run_processes
    process.start()
    │       └ <function BaseProcess.start at 0x7f2895f02040>
    └ <Process name='Process-1' parent=24849 started>

  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
    │    │        │    │      └ <Process name='Process-1' parent=24849 started>
    │    │        │    └ <staticmethod object at 0x7f2895e92760>
    │    │        └ <Process name='Process-1' parent=24849 started>
    │    └ None
    └ <Process name='Process-1' parent=24849 started>
  File "/usr/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           │                │                            └ <Process name='Process-1' parent=24849 started>
           │                └ <function DefaultContext.get_context at 0x7f2895ef0160>
           └ <multiprocessing.context.DefaultContext object at 0x7f2895f0e100>
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
           │     └ <Process name='Process-1' parent=24849 started>
           └ <class 'multiprocessing.popen_fork.Popen'>
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
    │    │       └ <Process name='Process-1' parent=24849 started>
    │    └ <function Popen._launch at 0x7f28920e60d0>
    └ <multiprocessing.popen_fork.Popen object at 0x7f289216eac0>
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 75, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
           │           │                          └ 7
           │           └ <function BaseProcess._bootstrap at 0x7f2895f02940>
           └ <Process name='Process-1' parent=24849 started>
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7f2895efdf70>
    └ <Process name='Process-1' parent=24849 started>
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Process name='Process-1' parent=24849 started>
    │    │        │    └ ((1254, 'коррекция зрения', '<?xml version="1.0" encoding="UTF-8" ?>\n<yandexsearch version="1.0">\n  <response date="2021032...
    │    │        └ <Process name='Process-1' parent=24849 started>
    │    └ <function Yandex at 0x7f2892145940>
    └ <Process name='Process-1' parent=24849 started>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 190, in __init__
    self.make_concurency_object()
    │    └ <function Yandex.make_concurency_object at 0x7f2892146040>
    └ <__main__.Yandex object at 0x7f2895eb5d60>

> File "/home/artur/concurent_site_release/new_requests_handler.py", line 268, in make_concurency_object
    self.concurency_object = Concurency(self.site_objects_list, self.stemmed_request, self.request)
    │    │                   │          │    │                  │    │                │    └ 'коррекция зрения'
    │    │                   │          │    │                  │    │                └ <__main__.Yandex object at 0x7f2895eb5d60>
    │    │                   │          │    │                  │    └ ['коррекция', 'зрение']
    │    │                   │          │    │                  └ <__main__.Yandex object at 0x7f2895eb5d60>
    │    │                   │          │    └ [<__main__.Site object at 0x7f2891a9c460>, <__main__.Site object at 0x7f2891a9c580>, <__main__.Site object at 0x7f2891a9c4f0>...
    │    │                   │          └ <__main__.Yandex object at 0x7f2895eb5d60>
    │    │                   └ <function Concurency at 0x7f2892147670>
    │    └ ''
    └ <__main__.Yandex object at 0x7f2895eb5d60>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 551, in __init__
    self.convert_vital_domains_to_sting()
    │    └ <function Concurency.convert_vital_domains_to_sting at 0x7f2892147dc0>
    └ <__main__.Concurency object at 0x7f2888884160>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 881, in convert_vital_domains_to_sting
    self.vital_domains.amount = len(self.vital_domains)
    │    │                          │    └ ['wikipedia.org', 'ProDoctorov.ru', 'zoon.ru', 'habr.com']
    │    │                          └ <__main__.Concurency object at 0x7f2888884160>
    │    └ ['wikipedia.org', 'ProDoctorov.ru', 'zoon.ru', 'habr.com']
    └ <__main__.Concurency object at 0x7f2888884160>

AttributeError: 'list' object has no attribute 'amount'
16:14:53 An error has been caught in function 'run', process 'Process-1' (25600), thread 'MainThread' (139812300470080):
Traceback (most recent call last):

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 887, in <module>
    Manager()
    └ <function Manager at 0x7f2895eb6550>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 25, in __init__
    self.run_processes()
    │    └ <function Manager.run_processes at 0x7f289213fca0>
    └ <__main__.Manager object at 0x7f28952476a0>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 47, in run_processes
    process.start()
    │       └ <function BaseProcess.start at 0x7f2895f02040>
    └ <Process name='Process-1' parent=24849 started>

  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
    │    │        │    │      └ <Process name='Process-1' parent=24849 started>
    │    │        │    └ <staticmethod object at 0x7f2895e92760>
    │    │        └ <Process name='Process-1' parent=24849 started>
    │    └ None
    └ <Process name='Process-1' parent=24849 started>
  File "/usr/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           │                │                            └ <Process name='Process-1' parent=24849 started>
           │                └ <function DefaultContext.get_context at 0x7f2895ef0160>
           └ <multiprocessing.context.DefaultContext object at 0x7f2895f0e100>
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
           │     └ <Process name='Process-1' parent=24849 started>
           └ <class 'multiprocessing.popen_fork.Popen'>
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
    │    │       └ <Process name='Process-1' parent=24849 started>
    │    └ <function Popen._launch at 0x7f28920e60d0>
    └ <multiprocessing.popen_fork.Popen object at 0x7f289216eac0>
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 75, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
           │           │                          └ 7
           │           └ <function BaseProcess._bootstrap at 0x7f2895f02940>
           └ <Process name='Process-1' parent=24849 started>
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7f2895efdf70>
    └ <Process name='Process-1' parent=24849 started>
> File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Process name='Process-1' parent=24849 started>
    │    │        │    └ ((1254, 'коррекция зрения', '<?xml version="1.0" encoding="UTF-8" ?>\n<yandexsearch version="1.0">\n  <response date="2021032...
    │    │        └ <Process name='Process-1' parent=24849 started>
    │    └ <function Yandex at 0x7f2892145940>
    └ <Process name='Process-1' parent=24849 started>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 191, in __init__
    self.prepare_result()
    │    └ <function Yandex.prepare_result at 0x7f28921460d0>
    └ <__main__.Yandex object at 0x7f2895eb5d60>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 273, in prepare_result
    'Конкуренция по возрасту': self.concurency_object.site_age_concurency,
                               │    └ None
                               └ <__main__.Yandex object at 0x7f2895eb5d60>

AttributeError: 'NoneType' object has no attribute 'site_age_concurency'
16:15:24 Не удалось загрузить https://www.nlv.ru/laser-correction
16:15:24 Проблема с валидностью контента nlv.ru. 
14:55:59 An error has been caught in function 'make_concurency_object', process 'Process-1' (19005), thread 'MainThread' (140530203260736):
Traceback (most recent call last):

  File "/home/artur/Загрузки/pycharm-2020.1.1/plugins/python/helpers/pydev/pydevd.py", line 2131, in <module>
    main()
    └ <function main at 0x7fcfbb79d310>

  File "/home/artur/Загрузки/pycharm-2020.1.1/plugins/python/helpers/pydev/pydevd.py", line 2122, in main
    globals = debugger.run(setup['file'], None, None, is_module)
              │        │   │                          └ False
              │        │   └ {'port': 38505, 'vm_type': None, 'client': '127.0.0.1', 'server': False, 'DEBUG_RECORD_SOCKET_READS': False, 'multiproc': Tru...
              │        └ <function PyDB.run at 0x7fcfbb79f310>
              └ <__main__.PyDB object at 0x7fcfbbdc9d90>

  File "/home/artur/Загрузки/pycharm-2020.1.1/plugins/python/helpers/pydev/pydevd.py", line 1431, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
           │    │     │          │               │            │     │        └ {'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <_frozen_importlib_external.SourceFileLoader obj...
           │    │     │          │               │            │     └ {'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <_frozen_importlib_external.SourceFileLoader obj...
           │    │     │          │               │            └ '/home/artur/concurent_site_release/new_requests_handler.py'
           │    │     │          │               └ None
           │    │     │          └ ''
           │    │     └ False
           │    └ <function PyDB._exec at 0x7fcfbb79f3a0>
           └ <__main__.PyDB object at 0x7fcfbbdc9d90>

  File "/home/artur/Загрузки/pycharm-2020.1.1/plugins/python/helpers/pydev/pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    │             │        │     │        └ {'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <_frozen_importlib_external.SourceFileLoader obj...
    │             │        │     └ {'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <_frozen_importlib_external.SourceFileLoader obj...
    │             │        └ '/home/artur/concurent_site_release/new_requests_handler.py'
    │             └ <function execfile at 0x7fcfbc4c0310>
    └ <module '_pydev_bundle.pydev_imports' from '/home/artur/Загрузки/pycharm-2020.1.1/plugins/python/helpers/pydev/_pydev_bundle/...

  File "/home/artur/Загрузки/pycharm-2020.1.1/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
                 │              │              │     └ {'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <_frozen_importlib_external.SourceFileLoader obj...
                 │              │              └ {'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <_frozen_importlib_external.SourceFileLoader obj...
                 │              └ '/home/artur/concurent_site_release/new_requests_handler.py'
                 └ 'from conc_settings import *\nfrom multiprocessing import Process, Queue\nfrom threading import Thread\nfrom loguru import lo...

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 892, in <module>
    Manager()
    └ <function Manager at 0x7fcfbb643b80>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 25, in __init__
    self.run_processes()
    │    └ <function Manager.run_processes at 0x7fcfb8093040>
    └ <__main__.Manager object at 0x7fcfb9986250>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 47, in run_processes
    process.start()
    │       └ <function BaseProcess.start at 0x7fcfb9cd5dc0>
    └ <Process name='Process-1' parent=18994 started>

  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
    │    │        │    │      └ <Process name='Process-1' parent=18994 started>
    │    │        │    └ <staticmethod object at 0x7fcfbb656c70>
    │    │        └ <Process name='Process-1' parent=18994 started>
    │    └ None
    └ <Process name='Process-1' parent=18994 started>
  File "/usr/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           │                │                            └ <Process name='Process-1' parent=18994 started>
           │                └ <function DefaultContext.get_context at 0x7fcfb9cf5820>
           └ <multiprocessing.context.DefaultContext object at 0x7fcfb9cf00a0>
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
           │     └ <Process name='Process-1' parent=18994 started>
           └ <class 'multiprocessing.popen_fork.Popen'>
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
    │    │       └ <Process name='Process-1' parent=18994 started>
    │    └ <function Popen._launch at 0x7fcfb804b430>
    └ <multiprocessing.popen_fork.Popen object at 0x7fcfb803e670>
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 75, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
           │           │                          └ 9
           │           └ <function BaseProcess._bootstrap at 0x7fcfb9ce8700>
           └ <Process name='Process-1' parent=18994 started>
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7fcfb9cd5d30>
    └ <Process name='Process-1' parent=18994 started>
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Process name='Process-1' parent=18994 started>
    │    │        │    └ ((1267, 'натяжные потолки абакан', '<?xml version="1.0" encoding="UTF-8" ?>\n<yandexsearch version="1.0">\n  <response date="...
    │    │        └ <Process name='Process-1' parent=18994 started>
    │    └ <function Yandex at 0x7fcfb8093ca0>
    └ <Process name='Process-1' parent=18994 started>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 190, in __init__
    self.make_concurency_object()
    │    └ <function Yandex.make_concurency_object at 0x7fcfb80943a0>
    └ <__main__.Yandex object at 0x7fcfb9ce1a30>

> File "/home/artur/concurent_site_release/new_requests_handler.py", line 268, in make_concurency_object
    self.concurency_object = Concurency(self.site_objects_list, self.stemmed_request, self.request)
    │    │                   │          │    │                  │    │                │    └ 'натяжные потолки абакан'
    │    │                   │          │    │                  │    │                └ <__main__.Yandex object at 0x7fcfb9ce1a30>
    │    │                   │          │    │                  │    └ ['натяжной', 'потолок', 'абакан']
    │    │                   │          │    │                  └ <__main__.Yandex object at 0x7fcfb9ce1a30>
    │    │                   │          │    └ [<__main__.Site object at 0x7fcfb8060100>, <__main__.Site object at 0x7fcfa8f7dbe0>, <__main__.Site object at 0x7fcfa8f7deb0>...
    │    │                   │          └ <__main__.Yandex object at 0x7fcfb9ce1a30>
    │    │                   └ <function Concurency at 0x7fcfb80969d0>
    │    └ ''
    └ <__main__.Yandex object at 0x7fcfb9ce1a30>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 521, in __init__
    self.check_site_object_type()
    │    └ <function Concurency.check_site_object_type at 0x7fcfb8096af0>
    └ <__main__.Concurency object at 0x7fcf7c74e0d0>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 560, in check_site_object_type
    if site_object.position <= 4:
       │           └ '1'
       └ <__main__.Site object at 0x7fcfb8060100>

TypeError: '<=' not supported between instances of 'str' and 'int'
14:55:59 An error has been caught in function 'run', process 'Process-1' (19005), thread 'MainThread' (140530203260736):
Traceback (most recent call last):

  File "/home/artur/Загрузки/pycharm-2020.1.1/plugins/python/helpers/pydev/pydevd.py", line 2131, in <module>
    main()
    └ <function main at 0x7fcfbb79d310>

  File "/home/artur/Загрузки/pycharm-2020.1.1/plugins/python/helpers/pydev/pydevd.py", line 2122, in main
    globals = debugger.run(setup['file'], None, None, is_module)
              │        │   │                          └ False
              │        │   └ {'port': 38505, 'vm_type': None, 'client': '127.0.0.1', 'server': False, 'DEBUG_RECORD_SOCKET_READS': False, 'multiproc': Tru...
              │        └ <function PyDB.run at 0x7fcfbb79f310>
              └ <__main__.PyDB object at 0x7fcfbbdc9d90>

  File "/home/artur/Загрузки/pycharm-2020.1.1/plugins/python/helpers/pydev/pydevd.py", line 1431, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
           │    │     │          │               │            │     │        └ {'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <_frozen_importlib_external.SourceFileLoader obj...
           │    │     │          │               │            │     └ {'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <_frozen_importlib_external.SourceFileLoader obj...
           │    │     │          │               │            └ '/home/artur/concurent_site_release/new_requests_handler.py'
           │    │     │          │               └ None
           │    │     │          └ ''
           │    │     └ False
           │    └ <function PyDB._exec at 0x7fcfbb79f3a0>
           └ <__main__.PyDB object at 0x7fcfbbdc9d90>

  File "/home/artur/Загрузки/pycharm-2020.1.1/plugins/python/helpers/pydev/pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    │             │        │     │        └ {'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <_frozen_importlib_external.SourceFileLoader obj...
    │             │        │     └ {'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <_frozen_importlib_external.SourceFileLoader obj...
    │             │        └ '/home/artur/concurent_site_release/new_requests_handler.py'
    │             └ <function execfile at 0x7fcfbc4c0310>
    └ <module '_pydev_bundle.pydev_imports' from '/home/artur/Загрузки/pycharm-2020.1.1/plugins/python/helpers/pydev/_pydev_bundle/...

  File "/home/artur/Загрузки/pycharm-2020.1.1/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
                 │              │              │     └ {'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <_frozen_importlib_external.SourceFileLoader obj...
                 │              │              └ {'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <_frozen_importlib_external.SourceFileLoader obj...
                 │              └ '/home/artur/concurent_site_release/new_requests_handler.py'
                 └ 'from conc_settings import *\nfrom multiprocessing import Process, Queue\nfrom threading import Thread\nfrom loguru import lo...

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 892, in <module>
    Manager()
    └ <function Manager at 0x7fcfbb643b80>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 25, in __init__
    self.run_processes()
    │    └ <function Manager.run_processes at 0x7fcfb8093040>
    └ <__main__.Manager object at 0x7fcfb9986250>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 47, in run_processes
    process.start()
    │       └ <function BaseProcess.start at 0x7fcfb9cd5dc0>
    └ <Process name='Process-1' parent=18994 started>

  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
    │    │        │    │      └ <Process name='Process-1' parent=18994 started>
    │    │        │    └ <staticmethod object at 0x7fcfbb656c70>
    │    │        └ <Process name='Process-1' parent=18994 started>
    │    └ None
    └ <Process name='Process-1' parent=18994 started>
  File "/usr/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           │                │                            └ <Process name='Process-1' parent=18994 started>
           │                └ <function DefaultContext.get_context at 0x7fcfb9cf5820>
           └ <multiprocessing.context.DefaultContext object at 0x7fcfb9cf00a0>
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
           │     └ <Process name='Process-1' parent=18994 started>
           └ <class 'multiprocessing.popen_fork.Popen'>
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
    │    │       └ <Process name='Process-1' parent=18994 started>
    │    └ <function Popen._launch at 0x7fcfb804b430>
    └ <multiprocessing.popen_fork.Popen object at 0x7fcfb803e670>
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 75, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
           │           │                          └ 9
           │           └ <function BaseProcess._bootstrap at 0x7fcfb9ce8700>
           └ <Process name='Process-1' parent=18994 started>
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7fcfb9cd5d30>
    └ <Process name='Process-1' parent=18994 started>
> File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Process name='Process-1' parent=18994 started>
    │    │        │    └ ((1267, 'натяжные потолки абакан', '<?xml version="1.0" encoding="UTF-8" ?>\n<yandexsearch version="1.0">\n  <response date="...
    │    │        └ <Process name='Process-1' parent=18994 started>
    │    └ <function Yandex at 0x7fcfb8093ca0>
    └ <Process name='Process-1' parent=18994 started>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 191, in __init__
    self.prepare_result()
    │    └ <function Yandex.prepare_result at 0x7fcfb8094430>
    └ <__main__.Yandex object at 0x7fcfb9ce1a30>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 273, in prepare_result
    'Конкуренция по возрасту': self.concurency_object.site_age_concurency,
                               │    └ None
                               └ <__main__.Yandex object at 0x7fcfb9ce1a30>

AttributeError: 'NoneType' object has no attribute 'site_age_concurency'
15:01:28 Не удалось загрузить https://www.nlv.ru/laser-correction
15:01:28 Проблема с валидностью контента nlv.ru. 
15:02:19 Не удалось загрузить https://www.nlv.ru/laser-correction
15:02:19 Проблема с валидностью контента nlv.ru. 
16:07:58 Не удалось загрузить https://www.nlv.ru/laser-correction
16:07:58 Проблема с валидностью контента nlv.ru. 
16:10:36 Проблема с валидностью контента юрист-мск.рф. 
15:50:39 Не удалось загрузить https://www.nlv.ru/laser-correction/lasik-operatsiya
15:50:39 Проблема с валидностью контента nlv.ru. 
17:31:17 Не удалось загрузить https://www.nlv.ru/laser-correction/lasik-operatsiya
17:31:17 Проблема с валидностью контента nlv.ru. 
18:21:47 Не удалось загрузить https://www.nlv.ru/laser-correction/lasik-operatsiya
18:21:47 Проблема с валидностью контента nlv.ru. 
16:23:49 Не удалось загрузить https://www.nlv.ru/laser-correction/lasik-operatsiya
16:23:49 Проблема с валидностью контента nlv.ru. 
16:23:56 Проблемы с доменом офтальма.рф
12:38:20 An error has been caught in function 'make_concurency_object', process 'Process-6' (4745), thread 'MainThread' (140081072482112):
Traceback (most recent call last):

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 922, in <module>
    Manager()
    └ <function Manager at 0x7f6729f34670>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 25, in __init__
    self.run_processes()
    │    └ <function Manager.run_processes at 0x7f672623cd30>
    └ <__main__.Manager object at 0x7f6729449ca0>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 55, in run_processes
    process.start()
    │       └ <function BaseProcess.start at 0x7f6729f410d0>
    └ <Process name='Process-6' parent=4499 started>

  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
    │    │        │    │      └ <Process name='Process-6' parent=4499 started>
    │    │        │    └ <staticmethod object at 0x7f6729f88790>
    │    │        └ <Process name='Process-6' parent=4499 started>
    │    └ None
    └ <Process name='Process-6' parent=4499 started>
  File "/usr/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           │                │                            └ <Process name='Process-6' parent=4499 started>
           │                └ <function DefaultContext.get_context at 0x7f672a0641f0>
           └ <multiprocessing.context.DefaultContext object at 0x7f6729f48100>
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
           │     └ <Process name='Process-6' parent=4499 started>
           └ <class 'multiprocessing.popen_fork.Popen'>
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
    │    │       └ <Process name='Process-6' parent=4499 started>
    │    └ <function Popen._launch at 0x7f67261e41f0>
    └ <multiprocessing.popen_fork.Popen object at 0x7f67262744c0>
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 75, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
           │           │                          └ 9
           │           └ <function BaseProcess._bootstrap at 0x7f6729f419d0>
           └ <Process name='Process-6' parent=4499 started>
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7f6729f41040>
    └ <Process name='Process-6' parent=4499 started>
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Process name='Process-6' parent=4499 started>
    │    │        │    └ ((211, 'стоимость нотариального оформления договора купли продажи квартиры', '<topads><query><url>uslugi.yandex.ru</url><titl...
    │    │        └ <Process name='Process-6' parent=4499 started>
    │    └ <function Yandex at 0x7f67262409d0>
    └ <Process name='Process-6' parent=4499 started>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 202, in __init__
    self.make_concurency_object()
    │    └ <function Yandex.make_concurency_object at 0x7f67262410d0>
    └ <__main__.Yandex object at 0x7f6729fa3d90>

> File "/home/artur/concurent_site_release/new_requests_handler.py", line 280, in make_concurency_object
    self.concurency_object = Concurency(self.site_objects_list, self.stemmed_request, self.request)
    │    │                   │          │    │                  │    │                │    └ 'стоимость нотариального оформления договора купли продажи квартиры'
    │    │                   │          │    │                  │    │                └ <__main__.Yandex object at 0x7f6729fa3d90>
    │    │                   │          │    │                  │    └ ['стоимость', 'нотариальный', 'оформление', 'договор', 'купля', 'продажа', 'квартира']
    │    │                   │          │    │                  └ <__main__.Yandex object at 0x7f6729fa3d90>
    │    │                   │          │    └ [<__main__.Site object at 0x7f6725b45b20>, <__main__.Site object at 0x7f6725b45c40>, <__main__.Site object at 0x7f6725b45bb0>...
    │    │                   │          └ <__main__.Yandex object at 0x7f6729fa3d90>
    │    │                   └ <function Concurency at 0x7f6726243700>
    │    └ ''
    └ <__main__.Yandex object at 0x7f6729fa3d90>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 542, in __init__
    self.calculate_site_stem_concurency()
    │    └ <function Concurency.calculate_site_stem_concurency at 0x7f67262439d0>
    └ <__main__.Concurency object at 0x7f6725acb820>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 637, in calculate_site_stem_concurency
    max_stem_concurency += self.WEIGHTS[site_object.position]
    │                      │    │       │           └ '33'
    │                      │    │       └ <__main__.Site object at 0x7f6725ad7d30>
    │                      │    └ {'1': 21, '2': 15, '3': 11, '4': 8, '5': 6, '6': 4, '7': 3, '8': 2, '9': 2, '10': 2, '11': 2, '12': 2, '13': 2, '14': 2, '15'...
    │                      └ <__main__.Concurency object at 0x7f6725acb820>
    └ 71

KeyError: '33'
12:38:20 An error has been caught in function 'run', process 'Process-6' (4745), thread 'MainThread' (140081072482112):
Traceback (most recent call last):

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 922, in <module>
    Manager()
    └ <function Manager at 0x7f6729f34670>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 25, in __init__
    self.run_processes()
    │    └ <function Manager.run_processes at 0x7f672623cd30>
    └ <__main__.Manager object at 0x7f6729449ca0>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 55, in run_processes
    process.start()
    │       └ <function BaseProcess.start at 0x7f6729f410d0>
    └ <Process name='Process-6' parent=4499 started>

  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
    │    │        │    │      └ <Process name='Process-6' parent=4499 started>
    │    │        │    └ <staticmethod object at 0x7f6729f88790>
    │    │        └ <Process name='Process-6' parent=4499 started>
    │    └ None
    └ <Process name='Process-6' parent=4499 started>
  File "/usr/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           │                │                            └ <Process name='Process-6' parent=4499 started>
           │                └ <function DefaultContext.get_context at 0x7f672a0641f0>
           └ <multiprocessing.context.DefaultContext object at 0x7f6729f48100>
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
           │     └ <Process name='Process-6' parent=4499 started>
           └ <class 'multiprocessing.popen_fork.Popen'>
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
    │    │       └ <Process name='Process-6' parent=4499 started>
    │    └ <function Popen._launch at 0x7f67261e41f0>
    └ <multiprocessing.popen_fork.Popen object at 0x7f67262744c0>
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 75, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
           │           │                          └ 9
           │           └ <function BaseProcess._bootstrap at 0x7f6729f419d0>
           └ <Process name='Process-6' parent=4499 started>
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7f6729f41040>
    └ <Process name='Process-6' parent=4499 started>
> File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Process name='Process-6' parent=4499 started>
    │    │        │    └ ((211, 'стоимость нотариального оформления договора купли продажи квартиры', '<topads><query><url>uslugi.yandex.ru</url><titl...
    │    │        └ <Process name='Process-6' parent=4499 started>
    │    └ <function Yandex at 0x7f67262409d0>
    └ <Process name='Process-6' parent=4499 started>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 203, in __init__
    self.prepare_result()
    │    └ <function Yandex.prepare_result at 0x7f6726241160>
    └ <__main__.Yandex object at 0x7f6729fa3d90>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 285, in prepare_result
    'Конкуренция по возрасту': self.concurency_object.site_age_concurency,
                               │    └ None
                               └ <__main__.Yandex object at 0x7f6729fa3d90>

AttributeError: 'NoneType' object has no attribute 'site_age_concurency'
12:39:34 An error has been caught in function 'make_concurency_object', process 'Process-2' (5102), thread 'MainThread' (140291171755840):
Traceback (most recent call last):

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 922, in <module>
    Manager()
    └ <function Manager at 0x7f9814d7c670>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 25, in __init__
    self.run_processes()
    │    └ <function Manager.run_processes at 0x7f981109cd30>
    └ <__main__.Manager object at 0x7f981419c6d0>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 55, in run_processes
    process.start()
    │       └ <function BaseProcess.start at 0x7f9814da30d0>
    └ <Process name='Process-2' parent=4997 started>

  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
    │    │        │    │      └ <Process name='Process-2' parent=4997 started>
    │    │        │    └ <staticmethod object at 0x7f9814dea760>
    │    │        └ <Process name='Process-2' parent=4997 started>
    │    └ None
    └ <Process name='Process-2' parent=4997 started>
  File "/usr/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           │                │                            └ <Process name='Process-2' parent=4997 started>
           │                └ <function DefaultContext.get_context at 0x7f9814e4b1f0>
           └ <multiprocessing.context.DefaultContext object at 0x7f9814d9dfa0>
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
           │     └ <Process name='Process-2' parent=4997 started>
           └ <class 'multiprocessing.popen_fork.Popen'>
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
    │    │       └ <Process name='Process-2' parent=4997 started>
    │    └ <function Popen._launch at 0x7f98110581f0>
    └ <multiprocessing.popen_fork.Popen object at 0x7f981104cac0>
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 75, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
           │           │                          └ 7
           │           └ <function BaseProcess._bootstrap at 0x7f9814da39d0>
           └ <Process name='Process-2' parent=4997 started>
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7f9814da3040>
    └ <Process name='Process-2' parent=4997 started>
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Process name='Process-2' parent=4997 started>
    │    │        │    └ ((211, 'стоимость нотариального оформления договора купли продажи квартиры', '<topads><query><url>uslugi.yandex.ru</url><titl...
    │    │        └ <Process name='Process-2' parent=4997 started>
    │    └ <function Yandex at 0x7f981109b9d0>
    └ <Process name='Process-2' parent=4997 started>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 202, in __init__
    self.make_concurency_object()
    │    └ <function Yandex.make_concurency_object at 0x7f98110a10d0>
    └ <__main__.Yandex object at 0x7f9814d90cd0>

> File "/home/artur/concurent_site_release/new_requests_handler.py", line 280, in make_concurency_object
    self.concurency_object = Concurency(self.site_objects_list, self.stemmed_request, self.request)
    │    │                   │          │    │                  │    │                │    └ 'стоимость нотариального оформления договора купли продажи квартиры'
    │    │                   │          │    │                  │    │                └ <__main__.Yandex object at 0x7f9814d90cd0>
    │    │                   │          │    │                  │    └ ['стоимость', 'нотариальный', 'оформление', 'договор', 'купля', 'продажа', 'квартира']
    │    │                   │          │    │                  └ <__main__.Yandex object at 0x7f9814d90cd0>
    │    │                   │          │    └ [<__main__.Site object at 0x7f98109a7400>, <__main__.Site object at 0x7f98109a7520>, <__main__.Site object at 0x7f98109a7490>...
    │    │                   │          └ <__main__.Yandex object at 0x7f9814d90cd0>
    │    │                   └ <function Concurency at 0x7f98110a2700>
    │    └ ''
    └ <__main__.Yandex object at 0x7f9814d90cd0>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 542, in __init__
    self.calculate_site_stem_concurency()
    │    └ <function Concurency.calculate_site_stem_concurency at 0x7f98110a29d0>
    └ <__main__.Concurency object at 0x7f9810926640>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 637, in calculate_site_stem_concurency
    max_stem_concurency += self.WEIGHTS[site_object.position]
    │                      │    │       │           └ '33'
    │                      │    │       └ <__main__.Site object at 0x7f98108bd820>
    │                      │    └ {'1': 21, '2': 15, '3': 11, '4': 8, '5': 6, '6': 4, '7': 3, '8': 2, '9': 2, '10': 2, '11': 2, '12': 2, '13': 2, '14': 2, '15'...
    │                      └ <__main__.Concurency object at 0x7f9810926640>
    └ 71

KeyError: '33'
12:39:34 An error has been caught in function 'run', process 'Process-2' (5102), thread 'MainThread' (140291171755840):
Traceback (most recent call last):

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 922, in <module>
    Manager()
    └ <function Manager at 0x7f9814d7c670>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 25, in __init__
    self.run_processes()
    │    └ <function Manager.run_processes at 0x7f981109cd30>
    └ <__main__.Manager object at 0x7f981419c6d0>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 55, in run_processes
    process.start()
    │       └ <function BaseProcess.start at 0x7f9814da30d0>
    └ <Process name='Process-2' parent=4997 started>

  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
    │    │        │    │      └ <Process name='Process-2' parent=4997 started>
    │    │        │    └ <staticmethod object at 0x7f9814dea760>
    │    │        └ <Process name='Process-2' parent=4997 started>
    │    └ None
    └ <Process name='Process-2' parent=4997 started>
  File "/usr/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           │                │                            └ <Process name='Process-2' parent=4997 started>
           │                └ <function DefaultContext.get_context at 0x7f9814e4b1f0>
           └ <multiprocessing.context.DefaultContext object at 0x7f9814d9dfa0>
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
           │     └ <Process name='Process-2' parent=4997 started>
           └ <class 'multiprocessing.popen_fork.Popen'>
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
    │    │       └ <Process name='Process-2' parent=4997 started>
    │    └ <function Popen._launch at 0x7f98110581f0>
    └ <multiprocessing.popen_fork.Popen object at 0x7f981104cac0>
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 75, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
           │           │                          └ 7
           │           └ <function BaseProcess._bootstrap at 0x7f9814da39d0>
           └ <Process name='Process-2' parent=4997 started>
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7f9814da3040>
    └ <Process name='Process-2' parent=4997 started>
> File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Process name='Process-2' parent=4997 started>
    │    │        │    └ ((211, 'стоимость нотариального оформления договора купли продажи квартиры', '<topads><query><url>uslugi.yandex.ru</url><titl...
    │    │        └ <Process name='Process-2' parent=4997 started>
    │    └ <function Yandex at 0x7f981109b9d0>
    └ <Process name='Process-2' parent=4997 started>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 203, in __init__
    self.prepare_result()
    │    └ <function Yandex.prepare_result at 0x7f98110a1160>
    └ <__main__.Yandex object at 0x7f9814d90cd0>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 285, in prepare_result
    'Конкуренция по возрасту': self.concurency_object.site_age_concurency,
                               │    └ None
                               └ <__main__.Yandex object at 0x7f9814d90cd0>

AttributeError: 'NoneType' object has no attribute 'site_age_concurency'
12:40:55 An error has been caught in function 'make_concurency_object', process 'Process-1' (5356), thread 'MainThread' (140225329702720):
Traceback (most recent call last):

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 922, in <module>
    Manager()
    └ <function Manager at 0x7f88c059c670>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 25, in __init__
    self.run_processes()
    │    └ <function Manager.run_processes at 0x7f88bc8a4d30>
    └ <__main__.Manager object at 0x7f88bf9a7490>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 55, in run_processes
    process.start()
    │       └ <function BaseProcess.start at 0x7f88c05aa0d0>
    └ <Process name='Process-1' parent=5354 started>

  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
    │    │        │    │      └ <Process name='Process-1' parent=5354 started>
    │    │        │    └ <staticmethod object at 0x7f88c05f0760>
    │    │        └ <Process name='Process-1' parent=5354 started>
    │    └ None
    └ <Process name='Process-1' parent=5354 started>
  File "/usr/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           │                │                            └ <Process name='Process-1' parent=5354 started>
           │                └ <function DefaultContext.get_context at 0x7f88c06cb1f0>
           └ <multiprocessing.context.DefaultContext object at 0x7f88c05b1100>
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
           │     └ <Process name='Process-1' parent=5354 started>
           └ <class 'multiprocessing.popen_fork.Popen'>
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
    │    │       └ <Process name='Process-1' parent=5354 started>
    │    └ <function Popen._launch at 0x7f88bc8491f0>
    └ <multiprocessing.popen_fork.Popen object at 0x7f88bc8d56a0>
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 75, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
           │           │                          └ 7
           │           └ <function BaseProcess._bootstrap at 0x7f88c05aa9d0>
           └ <Process name='Process-1' parent=5354 started>
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7f88c05aa040>
    └ <Process name='Process-1' parent=5354 started>
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Process name='Process-1' parent=5354 started>
    │    │        │    └ ((211, 'стоимость нотариального оформления договора купли продажи квартиры', '<topads><query><url>uslugi.yandex.ru</url><titl...
    │    │        └ <Process name='Process-1' parent=5354 started>
    │    └ <function Yandex at 0x7f88bc8a39d0>
    └ <Process name='Process-1' parent=5354 started>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 202, in __init__
    self.make_concurency_object()
    │    └ <function Yandex.make_concurency_object at 0x7f88bc8a80d0>
    └ <__main__.Yandex object at 0x7f88c060bd60>

> File "/home/artur/concurent_site_release/new_requests_handler.py", line 280, in make_concurency_object
    self.concurency_object = Concurency(self.site_objects_list, self.stemmed_request, self.request)
    │    │                   │          │    │                  │    │                │    └ 'стоимость нотариального оформления договора купли продажи квартиры'
    │    │                   │          │    │                  │    │                └ <__main__.Yandex object at 0x7f88c060bd60>
    │    │                   │          │    │                  │    └ ['стоимость', 'нотариальный', 'оформление', 'договор', 'купля', 'продажа', 'квартира']
    │    │                   │          │    │                  └ <__main__.Yandex object at 0x7f88c060bd60>
    │    │                   │          │    └ [<__main__.Site object at 0x7f88bc207cd0>, <__main__.Site object at 0x7f88bc207df0>, <__main__.Site object at 0x7f88bc207d60>...
    │    │                   │          └ <__main__.Yandex object at 0x7f88c060bd60>
    │    │                   └ <function Concurency at 0x7f88bc8ab700>
    │    └ ''
    └ <__main__.Yandex object at 0x7f88c060bd60>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 542, in __init__
    self.calculate_site_stem_concurency()
    │    └ <function Concurency.calculate_site_stem_concurency at 0x7f88bc8ab9d0>
    └ <__main__.Concurency object at 0x7f88bc207f70>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 637, in calculate_site_stem_concurency
    max_stem_concurency += self.WEIGHTS[site_object.position]
    │                      │    │       │           └ '33'
    │                      │    │       └ <__main__.Site object at 0x7f88bc136d90>
    │                      │    └ {'1': 21, '2': 15, '3': 11, '4': 8, '5': 6, '6': 4, '7': 3, '8': 2, '9': 2, '10': 2, '11': 2, '12': 2, '13': 2, '14': 2, '15'...
    │                      └ <__main__.Concurency object at 0x7f88bc207f70>
    └ 71

KeyError: '33'
12:40:55 An error has been caught in function 'run', process 'Process-1' (5356), thread 'MainThread' (140225329702720):
Traceback (most recent call last):

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 922, in <module>
    Manager()
    └ <function Manager at 0x7f88c059c670>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 25, in __init__
    self.run_processes()
    │    └ <function Manager.run_processes at 0x7f88bc8a4d30>
    └ <__main__.Manager object at 0x7f88bf9a7490>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 55, in run_processes
    process.start()
    │       └ <function BaseProcess.start at 0x7f88c05aa0d0>
    └ <Process name='Process-1' parent=5354 started>

  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
    │    │        │    │      └ <Process name='Process-1' parent=5354 started>
    │    │        │    └ <staticmethod object at 0x7f88c05f0760>
    │    │        └ <Process name='Process-1' parent=5354 started>
    │    └ None
    └ <Process name='Process-1' parent=5354 started>
  File "/usr/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           │                │                            └ <Process name='Process-1' parent=5354 started>
           │                └ <function DefaultContext.get_context at 0x7f88c06cb1f0>
           └ <multiprocessing.context.DefaultContext object at 0x7f88c05b1100>
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
           │     └ <Process name='Process-1' parent=5354 started>
           └ <class 'multiprocessing.popen_fork.Popen'>
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
    │    │       └ <Process name='Process-1' parent=5354 started>
    │    └ <function Popen._launch at 0x7f88bc8491f0>
    └ <multiprocessing.popen_fork.Popen object at 0x7f88bc8d56a0>
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 75, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
           │           │                          └ 7
           │           └ <function BaseProcess._bootstrap at 0x7f88c05aa9d0>
           └ <Process name='Process-1' parent=5354 started>
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7f88c05aa040>
    └ <Process name='Process-1' parent=5354 started>
> File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Process name='Process-1' parent=5354 started>
    │    │        │    └ ((211, 'стоимость нотариального оформления договора купли продажи квартиры', '<topads><query><url>uslugi.yandex.ru</url><titl...
    │    │        └ <Process name='Process-1' parent=5354 started>
    │    └ <function Yandex at 0x7f88bc8a39d0>
    └ <Process name='Process-1' parent=5354 started>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 203, in __init__
    self.prepare_result()
    │    └ <function Yandex.prepare_result at 0x7f88bc8a8160>
    └ <__main__.Yandex object at 0x7f88c060bd60>

  File "/home/artur/concurent_site_release/new_requests_handler.py", line 285, in prepare_result
    'Конкуренция по возрасту': self.concurency_object.site_age_concurency,
                               │    └ None
                               └ <__main__.Yandex object at 0x7f88c060bd60>

AttributeError: 'NoneType' object has no attribute 'site_age_concurency'
13:15:15 Проблема с валидностью контента юрист-мск.рф. 
13:15:16 Проблема с валидностью контента юрист-мск.рф. 
13:15:30 Проблема с валидностью контента юрист-мск.рф. 
13:15:45 Проблема с валидностью контента юрист-мск.рф. 
13:16:13 Проблема с валидностью контента юрист-мск.рф. 
13:16:13 Проблема с валидностью контента юрист-мск.рф. 
13:16:28 Проблема с валидностью контента юрист-мск.рф. 
13:16:42 Проблема с валидностью контента юрист-мск.рф. 
13:16:42 Проблема с валидностью контента юрист-мск.рф. 
13:16:56 Проблема с валидностью контента юрист-мск.рф. 
13:17:10 Проблема с валидностью контента юрист-мск.рф. 
13:17:10 Проблема с валидностью контента юрист-мск.рф. 
13:17:28 Проблема с валидностью контента юрист-мск.рф. 
13:18:31 Проблема с валидностью контента юрист-мск.рф. 
13:24:22 Не удалось загрузить https://retail-realty.ru/articles/item/oformlenie-sdelok-s-nedvizhimostyu-pokupka-prodazha-i-kak-izbezhat-obmana
13:24:22 Проблема с валидностью контента retail-realty.ru. 
13:24:34 Проблема с валидностью контента notary-msk.ru. 
13:25:21 Проблема с валидностью контента gov.ru. 
13:25:21 Проблема с валидностью контента gov.ru. 
13:25:21 Проблема с валидностью контента gov.ru. 
13:25:21 Проблема с валидностью контента gov.ru. 
13:25:22 Проблема с валидностью контента notary-msk.ru. 
13:25:36 Проблема с валидностью контента gov.ru. 
13:25:36 Проблема с валидностью контента gov.ru. 
13:25:38 Проблема с валидностью контента domofond.ru. 
13:25:55 Проблема с валидностью контента law.ru. 
13:26:10 Проблема с валидностью контента law.ru. 
13:26:10 Проблема с валидностью контента law.ru. 
13:26:24 Проблема с валидностью контента law.ru. 
13:26:25 Проблема с валидностью контента gov.ru. 
13:26:25 Проблема с валидностью контента gov.ru. 
13:26:39 Проблема с валидностью контента gov.ru. 
13:27:09 Не удалось загрузить https://forma-prava.ru/msk/uslugi/bankrotstvo-fizicheskih-lits/
13:27:09 Проблема с валидностью контента forma-prava.ru. 
13:27:35 Не удалось загрузить https://forma-prava.ru/msk/uslugi/bankrotstvo-fizicheskih-lits/
13:27:35 Проблема с валидностью контента forma-prava.ru. 
13:27:35 Не удалось загрузить https://forma-prava.ru/msk/
13:27:35 Проблема с валидностью контента forma-prava.ru. 
13:27:46 Проблема с валидностью контента gov.ru. 
13:27:46 Проблема с валидностью контента gov.ru. 
13:28:18 Проблема с валидностью контента law.ru. 
13:28:19 Проблема с валидностью контента Zarplata-online.ru. 
13:28:19 Проблема с валидностью контента business.ru. 
13:28:19 Проблема с валидностью контента law.ru. 
13:28:19 Проблема с валидностью контента dvitex.ru. 
13:28:35 Проблема с валидностью контента business.ru. 
13:28:36 Проблема с валидностью контента assistentus.ru. 
