15:25:43 An error has been caught in function 'make_site_object', process 'Process-1' (16542), thread 'Thread-30' (140628704884480):
Traceback (most recent call last):

  File "/home/wenfort/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       │    └ <function HTTPConnectionPool._make_request at 0x7fe714ef9820>
                       └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fe70674e1f0>
  File "/home/wenfort/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x7fe7140add60>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x7fe714ef9d30>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fe70674e1f0>
  File "/home/wenfort/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x7fe714ee8430>
    └ <urllib3.connection.HTTPSConnection object at 0x7fe7140add60>
  File "/home/wenfort/env/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
    │    │      └ <function ssl_wrap_socket at 0x7fe714edd160>
    │    └ None
    └ <urllib3.connection.HTTPSConnection object at 0x7fe7140add60>
  File "/home/wenfort/env/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               └ <function _ssl_wrap_socket_impl at 0x7fe714edd310>
  File "/home/wenfort/env/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           │           │           │                     └ 'www.nlv.ru'
           │           │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
           │           └ <function SSLContext.wrap_socket at 0x7fe7157d7700>
           └ <ssl.SSLContext object at 0x7fe70683e6c0>
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod object at 0x7fe7157d5eb0>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x7fe70683e6c0>
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0x7fe7157db5e0>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

ssl.SSLError: [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1123)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/wenfort/env/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x7fe714ef9a60>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fe70674e1f0>
  File "/home/wenfort/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
              │       └ <function Retry.increment at 0x7fe714e305e0>
              └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
  File "/home/wenfort/env/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1123)'))
          │             │      └ '/laser-correction/lasik-operatsiya'
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fe70674e1f0>
          └ <class 'urllib3.exceptions.MaxRetryError'>

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.nlv.ru', port=443): Max retries exceeded with url: /laser-correction/lasik-operatsiya (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1123)')))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/wenfort/Загрузки/pycharm-2020.1/plugins/python/helpers/pydev/_pydev_bundle/pydev_monkey.py", line 770, in __call__
    ret = self.original_func(*self.args, **self.kwargs)
          │    │              │    │       │    └ {}
          │    │              │    │       └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x7fe706783fd0>
          │    │              │    └ ()
          │    │              └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x7fe706783fd0>
          │    └ <bound method Thread._bootstrap of <Thread(Thread-30, started 140628704884480)>>
          └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x7fe706783fd0>

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe715e6baf0>
    └ <Thread(Thread-30, started 140628704884480)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe715e6b820>
    └ <Thread(Thread-30, started 140628704884480)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-30, started 140628704884480)>
    │    │        │    └ (SiteDataSet(html=<doc><url>https://www.nlv.ru/laser-correction/lasik-operatsiya</url><title>ЛАСИК ( LASIK ) лазерная коррекц...
    │    │        └ <Thread(Thread-30, started 140628704884480)>
    │    └ <bound method Yandex.make_site_object of <__main__.Yandex object at 0x7fe7145ad460>>
    └ <Thread(Thread-30, started 140628704884480)>

> File "/home/wenfort/PycharmProjects/concurent_site_release/microservices/new_requests_handler.py", line 348, in make_site_object
    self.site_objects_list.append(Site(site_dataset))
    │    │                 │      │    └ SiteDataSet(html=<doc><url>https://www.nlv.ru/laser-correction/lasik-operatsiya</url><title>ЛАСИК ( LASIK ) лазерная коррекци...
    │    │                 │      └ <function Site at 0x7fe7140cfa60>
    │    │                 └ <method 'append' of 'list' objects>
    │    └ [<__main__.Site object at 0x7fe706783850>]
    └ <__main__.Yandex object at 0x7fe7145ad460>

  File "/home/wenfort/PycharmProjects/concurent_site_release/microservices/new_requests_handler.py", line 171, in __init__
    self.get_html()
    │    └ <function Site.get_html at 0x7fe7140cfdc0>
    └ <__main__.Site object at 0x7fe70679c520>

  File "/home/wenfort/PycharmProjects/concurent_site_release/microservices/new_requests_handler.py", line 235, in get_html
    r = requests.get(self.url, headers=HEADERS, verify=False, timeout=15).content
        │        │   │    │            └ {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/...
        │        │   │    └ 'https://www.nlv.ru/laser-correction/lasik-operatsiya'
        │        │   └ <__main__.Site object at 0x7fe70679c520>
        │        └ <function get at 0x7fe714470040>
        └ <module 'requests' from '/home/wenfort/env/lib/python3.8/site-packages/requests/__init__.py'>

  File "/home/wenfort/env/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
           │              │           │         └ {'headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147...
           │              │           └ None
           │              └ 'https://www.nlv.ru/laser-correction/lasik-operatsiya'
           └ <function request at 0x7fe71445de50>
  File "/home/wenfort/env/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │       │              │           │      └ {'params': None, 'headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) ...
           │       │              │           └ 'https://www.nlv.ru/laser-correction/lasik-operatsiya'
           │       │              └ 'get'
           │       └ <function Session.request at 0x7fe714472790>
           └ <requests.sessions.Session object at 0x7fe706746e80>
  File "/home/wenfort/env/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': 15, 'allow_redirects': True, 'verify': False, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x7fe714472c10>
           └ <requests.sessions.Session object at 0x7fe706746e80>
  File "/home/wenfort/env/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'timeout': 15, 'verify': False, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
        │       │    └ <PreparedRequest [GET]>
        │       └ <function HTTPAdapter.send at 0x7fe7144720d0>
        └ <requests.adapters.HTTPAdapter object at 0x7fe706746eb0>
  File "/home/wenfort/env/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
          │                   └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.SSLError'>

requests.exceptions.SSLError: HTTPSConnectionPool(host='www.nlv.ru', port=443): Max retries exceeded with url: /laser-correction/lasik-operatsiya (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1123)')))
15:27:33 An error has been caught in function 'make_site_object', process 'Process-1' (16650), thread 'Thread-30' (140076466042624):
Traceback (most recent call last):

  File "/home/wenfort/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       │    └ <function HTTPConnectionPool._make_request at 0x7f6680989820>
                       └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7f667274dcd0>
  File "/home/wenfort/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x7f667274daf0>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x7f6680989d30>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7f667274dcd0>
  File "/home/wenfort/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x7f6680978430>
    └ <urllib3.connection.HTTPSConnection object at 0x7f667274daf0>
  File "/home/wenfort/env/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
    │    │      └ <function ssl_wrap_socket at 0x7f668096f160>
    │    └ None
    └ <urllib3.connection.HTTPSConnection object at 0x7f667274daf0>
  File "/home/wenfort/env/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               └ <function _ssl_wrap_socket_impl at 0x7f668096f310>
  File "/home/wenfort/env/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           │           │           │                     └ 'www.nlv.ru'
           │           │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
           │           └ <function SSLContext.wrap_socket at 0x7f66812a9700>
           └ <ssl.SSLContext object at 0x7f667235c9c0>
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod object at 0x7f66812a7eb0>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x7f667235c9c0>
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0x7f66812ad5e0>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

ssl.SSLError: [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1123)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/wenfort/env/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x7f6680989a60>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7f667274dcd0>
  File "/home/wenfort/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
              │       └ <function Retry.increment at 0x7f6680a3f5e0>
              └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
  File "/home/wenfort/env/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1123)'))
          │             │      └ '/laser-correction/lasik-operatsiya'
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7f667274dcd0>
          └ <class 'urllib3.exceptions.MaxRetryError'>

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.nlv.ru', port=443): Max retries exceeded with url: /laser-correction/lasik-operatsiya (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1123)')))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/wenfort/Загрузки/pycharm-2020.1/plugins/python/helpers/pydev/_pydev_bundle/pydev_monkey.py", line 770, in __call__
    ret = self.original_func(*self.args, **self.kwargs)
          │    │              │    │       │    └ {}
          │    │              │    │       └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x7f66722a3a60>
          │    │              │    └ ()
          │    │              └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x7f66722a3a60>
          │    └ <bound method Thread._bootstrap of <Thread(Thread-30, started 140076466042624)>>
          └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x7f66722a3a60>

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f668193daf0>
    └ <Thread(Thread-30, started 140076466042624)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f668193d820>
    └ <Thread(Thread-30, started 140076466042624)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-30, started 140076466042624)>
    │    │        │    └ (SiteDataSet(html=<doc><url>https://www.nlv.ru/laser-correction/lasik-operatsiya</url><title>ЛАСИК ( LASIK ) лазерная коррекц...
    │    │        └ <Thread(Thread-30, started 140076466042624)>
    │    └ <bound method Yandex.make_site_object of <__main__.Yandex object at 0x7f668007e4c0>>
    └ <Thread(Thread-30, started 140076466042624)>

> File "/home/wenfort/PycharmProjects/concurent_site_release/microservices/new_requests_handler.py", line 348, in make_site_object
    Site(site_dataset)
    │    └ SiteDataSet(html=<doc><url>https://www.nlv.ru/laser-correction/lasik-operatsiya</url><title>ЛАСИК ( LASIK ) лазерная коррекци...
    └ <function Site at 0x7f667802aa60>

  File "/home/wenfort/PycharmProjects/concurent_site_release/microservices/new_requests_handler.py", line 171, in __init__
    self.get_html()
    │    └ <function Site.get_html at 0x7f667802adc0>
    └ <__main__.Site object at 0x7f6672258d30>

  File "/home/wenfort/PycharmProjects/concurent_site_release/microservices/new_requests_handler.py", line 235, in get_html
    r = requests.get(self.url, headers=HEADERS, verify=False, timeout=15).content
        │        │   │    │            └ {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/...
        │        │   │    └ 'https://www.nlv.ru/laser-correction/lasik-operatsiya'
        │        │   └ <__main__.Site object at 0x7f6672258d30>
        │        └ <function get at 0x7f667af2e040>
        └ <module 'requests' from '/home/wenfort/env/lib/python3.8/site-packages/requests/__init__.py'>

  File "/home/wenfort/env/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
           │              │           │         └ {'headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147...
           │              │           └ None
           │              └ 'https://www.nlv.ru/laser-correction/lasik-operatsiya'
           └ <function request at 0x7f667af16e50>
  File "/home/wenfort/env/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │       │              │           │      └ {'params': None, 'headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) ...
           │       │              │           └ 'https://www.nlv.ru/laser-correction/lasik-operatsiya'
           │       │              └ 'get'
           │       └ <function Session.request at 0x7f667af2f790>
           └ <requests.sessions.Session object at 0x7f6672258cd0>
  File "/home/wenfort/env/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': 15, 'allow_redirects': True, 'verify': False, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x7f667af2fc10>
           └ <requests.sessions.Session object at 0x7f6672258cd0>
  File "/home/wenfort/env/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'timeout': 15, 'verify': False, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
        │       │    └ <PreparedRequest [GET]>
        │       └ <function HTTPAdapter.send at 0x7f667af2f0d0>
        └ <requests.adapters.HTTPAdapter object at 0x7f6672258eb0>
  File "/home/wenfort/env/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
          │                   └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.SSLError'>

requests.exceptions.SSLError: HTTPSConnectionPool(host='www.nlv.ru', port=443): Max retries exceeded with url: /laser-correction/lasik-operatsiya (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1123)')))
